// SPDX-License-Identifier: Apache-2.0

//! Integration replay of the language-neutral conformance corpus
//! (`schemas/v1/examples/conformance`; plan Sections 7.1–7.5 and 8).
//!
//! Where [`archivist_protocol::json`] is used to read the corpus files, the
//! crate's own owned parser is the reader — the bead's no-new-dependencies
//! rule — and every assertion compares bytes, not re-serialized text: the
//! canonical forms, digests, identifiers, object keys, and signing preimages
//! this crate computes from each vector's own inputs must equal the pinned
//! golden exactly or the vector's name appears in the failure.
//!
//! The corpus is generated by `tools/conformancegen.py`; this file asserts
//! the *Rust* side of the language-neutral contract (the generator's own
//! `--verify` and the standalone `tools/contract-verifier.py` cover the
//! generator and the cross-implementation comparison). Layers beyond the
//! protocol crate — Ed25519 verification, the receipt chain, authorization
//! windows — are pinned by those tools and live in `archivist-auth`.

use std::fs;
use std::path::{Path, PathBuf};
use std::str::FromStr;

use archivist_protocol::derivation;
use archivist_protocol::envelope::Envelope;
use archivist_protocol::json::{self, Value};
use archivist_protocol::object_key::{AttestationObjectKey, BlobObjectKey, OccurrenceObjectKey};
use archivist_protocol::sha256;
use archivist_protocol::vocabulary::{
    AdapterId, ArtifactHash, ArtifactKind, AttestationId, BlobDigest, ClientId, ContentType,
    Ed25519PublicKey, EnvelopeDigest, GenerationId, GrammarError, HarnessId, IncomingChecksum,
    KeyId, OccurrenceId, OpaqueId, RangeKind, RequestContentDigest, RequestId, SessionHash,
    StorageProfile, TenantId, Timestamp, VersionToken,
};

/// The committed corpus, relative to this crate's manifest directory.
fn corpus_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../schemas/v1/examples/conformance")
}

/// Read one corpus file, failing with its repository-relative path.
fn read(root: &Path, rel: &str) -> Result<Vec<u8>, String> {
    fs::read(root.join(rel)).map_err(|e| format!("{rel}: {e}"))
}

/// Read and parse one corpus JSON file.
fn load_json(root: &Path, rel: &str) -> Result<Value, String> {
    json::parse(&read(root, rel)?).map_err(|e| format!("{rel}: {e}"))
}

/// Require an object member.
fn member<'a>(value: &'a Value, rel: &str, name: &str) -> Result<&'a Value, String> {
    let Value::Object(object) = value else {
        return Err(format!("{rel}: expected an object"));
    };
    object
        .get(name)
        .ok_or_else(|| format!("{rel}: member {name} is missing"))
}

/// An optional member, `None` when absent.
fn optional<'a>(value: &'a Value, name: &str) -> Option<&'a Value> {
    match value {
        Value::Object(object) => object.get(name),
        _ => None,
    }
}

/// An optional member's text, `None` when absent or not a string.
fn text_member<'a>(value: &'a Value, name: &str) -> Option<&'a str> {
    match optional(value, name) {
        Some(Value::Text(text)) => Some(text.as_str()),
        _ => None,
    }
}

/// Require a text member.
fn text<'a>(value: &'a Value, rel: &str, name: &str) -> Result<&'a str, String> {
    match member(value, rel, name)? {
        Value::Text(text) => Ok(text),
        _ => Err(format!("{rel}: member {name} is not a string")),
    }
}

/// Require a `u63` member.
fn u63(value: &Value, rel: &str, name: &str) -> Result<u64, String> {
    match member(value, rel, name)? {
        Value::Int(n) if *n >= 0 => {
            u64::try_from(*n).map_err(|_| format!("{rel}: {name} overflow"))
        }
        _ => Err(format!("{rel}: member {name} is not a u63 integer")),
    }
}

/// Require a boolean member.
fn boolean(value: &Value, rel: &str, name: &str) -> Result<bool, String> {
    match member(value, rel, name)? {
        Value::Bool(flag) => Ok(*flag),
        _ => Err(format!("{rel}: member {name} is not a boolean")),
    }
}

/// Require an array member.
fn array<'a>(value: &'a Value, rel: &str, name: &str) -> Result<&'a [Value], String> {
    match member(value, rel, name)? {
        Value::Array(items) => Ok(items),
        _ => Err(format!("{rel}: member {name} is not an array")),
    }
}

/// Parse a text member through a grammar newtype.
fn parsed<T>(value: &Value, rel: &str, name: &str) -> Result<T, String>
where
    T: FromStr<Err = GrammarError>,
{
    let raw = text(value, rel, name)?;
    T::from_str(raw).map_err(|_| format!("{rel}: member {name} fails its grammar: {raw}"))
}

/// Lowercase hex of `bytes`.
fn hex(bytes: &[u8]) -> String {
    sha256::encode_hex(bytes)
}

/// Lowercase hex of the SHA-256 digest of `bytes`.
fn sha256_hex(bytes: &[u8]) -> String {
    hex(&sha256::digest(bytes))
}

/// The identity-input tuple every derivation construction consumes, read from
/// either a `derivations.json` case (`canonical_payload` names the payload
/// bytes) or a scenario envelope value (`blob_digest` names the digest).
struct IdentityInputs {
    tenant: TenantId,
    origin: ClientId,
    harness: HarnessId,
    upstream: OpaqueId,
    kind: ArtifactKind,
    adapter: AdapterId,
    projection: VersionToken,
    artifact_id: OpaqueId,
    generation: GenerationId,
    range_kind: RangeKind,
    range_start: u64,
    range_end: u64,
    blob: BlobDigest,
    uploader: ClientId,
    request: RequestId,
}

impl IdentityInputs {
    /// Read the inputs from a `derivations.json` case's `inputs` member.
    fn from_derivation_case(value: &Value, rel: &str) -> Result<Self, String> {
        let payload = text(value, rel, "canonical_payload")?;
        Self::new(
            value,
            rel,
            BlobDigest::from_raw(sha256::digest(payload.as_bytes())),
        )
    }

    /// Read the inputs from a scenario envelope's parsed JSON value.
    fn from_envelope_value(value: &Value, rel: &str) -> Result<Self, String> {
        Self::new(value, rel, parsed(value, rel, "blob_digest")?)
    }

    fn new(value: &Value, rel: &str, blob: BlobDigest) -> Result<Self, String> {
        Ok(Self {
            tenant: parsed(value, rel, "tenant_id")?,
            origin: parsed(value, rel, "origin_client_id")?,
            harness: parsed(value, rel, "harness")?,
            upstream: parsed(value, rel, "upstream_session_id")?,
            kind: parsed(value, rel, "artifact_kind")?,
            adapter: parsed(value, rel, "adapter_id")?,
            projection: parsed(value, rel, "adapter_projection_version")?,
            artifact_id: parsed(value, rel, "adapter_artifact_id")?,
            generation: parsed(value, rel, "generation")?,
            range_kind: parsed(value, rel, "range_kind")?,
            range_start: u63(value, rel, "range_start")?,
            range_end: u63(value, rel, "range_end")?,
            blob,
            uploader: parsed(value, rel, "uploader_client_id")?,
            request: parsed(value, rel, "request_id")?,
        })
    }
}

/// Every derived identity of one input tuple.
struct Derived {
    session: SessionHash,
    artifact: ArtifactHash,
    occurrence: OccurrenceId,
    attestation: AttestationId,
    blob: BlobDigest,
}

/// Derive every identity construction from the inputs.
fn derive(inputs: &IdentityInputs) -> Derived {
    let session = derivation::session_hash(
        &inputs.tenant,
        &inputs.origin,
        &inputs.harness,
        inputs.upstream.as_str(),
    );
    let artifact = derivation::artifact_hash(
        &session,
        inputs.kind,
        &inputs.adapter,
        &inputs.projection,
        inputs.artifact_id.as_str(),
    );
    let occurrence = derivation::occurrence_id(
        &session,
        &artifact,
        &inputs.generation,
        inputs.range_kind,
        inputs.range_start,
        inputs.range_end,
        &inputs.blob,
    );
    let attestation = derivation::attestation_id(&occurrence, &inputs.uploader, &inputs.request);
    Derived {
        session,
        artifact,
        occurrence,
        attestation,
        blob: inputs.blob,
    }
}

/// Compare a full derivation against a manifest `identity` block member by
/// member, naming each disagreeing field.
fn assert_identity_block(
    inputs: &IdentityInputs,
    identity: &Value,
    rel: &str,
    failures: &mut Vec<String>,
) {
    let derived = derive(inputs);
    let blob_key = BlobObjectKey::new(&inputs.tenant, StorageProfile::ZstdV1, &derived.blob);
    let occurrence_key = OccurrenceObjectKey::new(
        &inputs.tenant,
        &inputs.origin,
        &inputs.harness,
        &derived.session,
        &derived.occurrence,
    );
    let attestation_key =
        AttestationObjectKey::new(&inputs.tenant, &derived.occurrence, &derived.attestation);
    for (field, computed) in [
        ("session_hash", derived.session.to_hex()),
        ("artifact_hash", derived.artifact.to_hex()),
        ("occurrence_id", derived.occurrence.to_hex()),
        ("attestation_id", derived.attestation.to_hex()),
        ("blob_digest", derived.blob.to_hex()),
        ("blob_object_key", blob_key.to_string()),
        ("occurrence_object_key", occurrence_key.to_string()),
        ("attestation_object_key", attestation_key.to_string()),
    ] {
        let expected = text(identity, rel, field).unwrap_or("<missing>");
        if computed != expected {
            failures.push(format!(
                "{rel}: {field}: computed {computed}, pinned {expected}"
            ));
        }
    }
}

/// Assert `condition`, recording `context` when it does not hold.
fn demand(failures: &mut Vec<String>, context: String, condition: bool) {
    if !condition {
        failures.push(context);
    }
}

/// The manifest's scenario entries.
fn scenarios(manifest: &Value) -> Result<&[Value], String> {
    array(manifest, "manifest.json", "scenarios")
}

/// One scenario's `identity` block.
fn identity_block<'a>(scenario: &'a Value, id: &str) -> Result<&'a Value, String> {
    member(scenario, &format!("scenario {id}"), "identity")
}

/// The whole corpus: every file the manifest lists exists with exactly the
/// pinned byte length and SHA-256, and every scenario-referenced file and
/// every file on disk is covered by that listing.
#[test]
fn corpus_files_match_the_manifest_listing() {
    let root = corpus_root();
    let manifest = load_json(&root, "manifest.json").unwrap();
    let listed = array(&manifest, "manifest.json", "files").unwrap();
    let mut failures = Vec::new();

    let mut listed_paths = Vec::new();
    for entry in listed {
        let rel = text(entry, "manifest.json files", "path")
            .unwrap()
            .to_owned();
        listed_paths.push(rel.clone());
        let bytes = read(&root, &rel).unwrap_or_else(|e| {
            failures.push(e);
            Vec::new()
        });
        let pinned_bytes = u63(entry, &rel, "bytes").unwrap();
        demand(
            &mut failures,
            format!(
                "{rel}: {} bytes on disk, {pinned_bytes} pinned",
                bytes.len()
            ),
            bytes.len() as u64 == pinned_bytes,
        );
        let pinned_sha = text(entry, &rel, "sha256").unwrap();
        demand(
            &mut failures,
            format!(
                "{rel}: sha256 {} computed, {pinned_sha} pinned",
                sha256_hex(&bytes)
            ),
            sha256_hex(&bytes) == pinned_sha,
        );
    }

    // Every scenario-referenced file is listed.
    for scenario in scenarios(&manifest).unwrap() {
        let id = text(scenario, "manifest.json", "id").unwrap();
        if let Value::Object(files) = member(scenario, id, "files").unwrap() {
            for (_, value) in files.iter() {
                if let Value::Text(rel) = value {
                    demand(
                        &mut failures,
                        format!("scenario {id}: {rel} is not in the manifest listing"),
                        listed_paths.contains(rel),
                    );
                }
            }
        }
    }

    // Every file on disk under scenarios/ is listed (no orphans).
    let scenario_dir = root.join("scenarios");
    let mut disk_paths = Vec::new();
    collect_relative(&scenario_dir, &scenario_dir, &mut disk_paths);
    for rel in disk_paths {
        demand(
            &mut failures,
            format!("scenarios/{rel} exists on disk but is not listed"),
            listed_paths.contains(&format!("scenarios/{rel}")),
        );
    }

    assert!(
        failures.is_empty(),
        "{} corpus listing failures:\n  {}",
        failures.len(),
        failures.join("\n  ")
    );
}

/// Recursively collect `dir`'s file paths relative to `base`, as `/`-joined
/// text.
fn collect_relative(dir: &Path, base: &Path, out: &mut Vec<String>) {
    let Ok(entries) = fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect_relative(&path, base, out);
        } else if let Ok(rel) = path.strip_prefix(base) {
            out.push(rel.to_string_lossy().replace('\\', "/"));
        }
    }
}

/// The corpus's own byte conventions: metadata files are canonical JSON plus
/// exactly one trailing LF; a wire-canonical envelope file is exactly its
/// canonical bytes (no LF); the one deliberately reordered envelope parses
/// but does not equal its canonical bytes.
#[test]
fn corpus_files_follow_the_pinned_byte_conventions() {
    let root = corpus_root();
    let manifest = load_json(&root, "manifest.json").unwrap();
    let mut failures = Vec::new();

    for entry in array(&manifest, "manifest.json", "files").unwrap() {
        let rel = text(entry, "manifest.json files", "path")
            .unwrap()
            .to_owned();
        if Path::new(&rel).extension().is_none_or(|ext| ext != "json") || rel == "manifest.json" {
            continue;
        }
        let bytes = read(&root, &rel).unwrap();
        let value = json::parse(&bytes)
            .map_err(|e| format!("{rel}: {e}"))
            .unwrap();
        let canonical = value.canonical_bytes();
        if rel.ends_with("/envelope.json") {
            let id = rel
                .strip_prefix("scenarios/")
                .and_then(|s| s.split('/').next());
            let scenario = scenarios(&manifest)
                .unwrap()
                .iter()
                .find(|s| text(s, "manifest.json", "id").unwrap() == id.unwrap_or_default());
            let wire_canonical = scenario
                .and_then(|s| optional(s, "envelope_wire_canonical"))
                .is_some_and(|v| matches!(v, Value::Bool(true)));
            if wire_canonical {
                demand(
                    &mut failures,
                    format!("{rel}: envelope file is not its exact canonical bytes"),
                    canonical == bytes,
                );
            } else {
                // The deliberate exception: reordered framing parses to the
                // same value but differs from the canonical bytes.
                demand(
                    &mut failures,
                    format!("{rel}: reordered envelope equals its canonical bytes"),
                    canonical != bytes,
                );
            }
        } else {
            let mut expected = canonical;
            expected.push(b'\n');
            demand(
                &mut failures,
                format!("{rel}: metadata file is not canonical JSON plus one LF"),
                expected == bytes,
            );
        }
    }

    assert!(
        failures.is_empty(),
        "{} byte-convention failures:\n  {}",
        failures.len(),
        failures.join("\n  ")
    );
}

/// `canonicalization.json` accept cases: the owned canonicalizer reproduces
/// every pinned canonical byte form, and the corpus's own digest pins hold.
#[test]
fn canonicalization_cases_replay_byte_for_byte() {
    let root = corpus_root();
    let table = load_json(&root, "canonicalization.json").unwrap();
    let cases = array(&table, "canonicalization.json", "cases").unwrap();
    let mut failures = Vec::new();

    let canonical_of = |case: &Value, name: &str| -> Option<Vec<u8>> {
        optional(case, name).map(Value::canonical_bytes)
    };

    for case in cases {
        let id = text(case, "canonicalization.json", "id").unwrap();
        let rel = format!("canonicalization.json case {id}");
        if let Some(canonical) = canonical_of(case, "object") {
            let pinned = text(case, &rel, "canonical_hex").unwrap();
            demand(
                &mut failures,
                format!(
                    "{rel}: canonical {} computed, {pinned} pinned",
                    hex(&canonical)
                ),
                hex(&canonical) == pinned,
            );
            let pinned_sha = text(case, &rel, "sha256").unwrap();
            demand(
                &mut failures,
                format!("{rel}: sha256 of canonical bytes disagrees"),
                sha256_hex(&canonical) == pinned_sha,
            );
        }
        if let Some(Value::Text(wire)) = optional(case, "noncanonical_text") {
            let value = json::parse(wire.as_bytes())
                .map_err(|e| format!("{rel}: noncanonical_text: {e}"))
                .unwrap();
            let pinned_sha = text(case, &rel, "sha256").unwrap();
            demand(
                &mut failures,
                format!("{rel}: noncanonical text digest disagrees"),
                sha256_hex(&value.canonical_bytes()) == pinned_sha,
            );
            let same = text(case, &rel, "same_canonical_as").unwrap();
            let twin = cases
                .iter()
                .find(|c| text(c, "canonicalization.json", "id").unwrap() == same);
            if let Some(twin) = twin {
                let twin_canonical = canonical_of(twin, "object");
                demand(
                    &mut failures,
                    format!("{rel}: does not canonicalize to {same}'s bytes"),
                    twin_canonical.is_some_and(|t| t == value.canonical_bytes()),
                );
            } else {
                failures.push(format!("{rel}: same_canonical_as {same} not found"));
            }
        }
        if optional(case, "nfc").is_some() {
            let nfc = canonical_of(case, "nfc").unwrap();
            let nfd = canonical_of(case, "nfd").unwrap();
            demand(
                &mut failures,
                format!("{rel}: nfc digest disagrees"),
                sha256_hex(&nfc) == text(case, &rel, "nfc_sha256").unwrap(),
            );
            demand(
                &mut failures,
                format!("{rel}: nfd digest disagrees"),
                sha256_hex(&nfd) == text(case, &rel, "nfd_sha256").unwrap(),
            );
            demand(
                &mut failures,
                format!("{rel}: composed and decomposed forms canonicalize alike"),
                nfc != nfd,
            );
        }
    }

    assert!(
        failures.is_empty(),
        "{} canonicalization failures:\n  {}",
        failures.len(),
        failures.join("\n  ")
    );
}

/// `canonicalization.json` rejections: the bounded parser refuses each
/// pinned malformed input, mapped to the wire code the corpus pins.
#[test]
fn canonicalization_rejections_map_to_their_wire_codes() {
    let root = corpus_root();
    let table = load_json(&root, "canonicalization.json").unwrap();
    let rejections = array(&table, "canonicalization.json", "rejections").unwrap();
    let mut failures = Vec::new();

    for rejection in rejections {
        let id = text(rejection, "canonicalization.json", "id").unwrap();
        let rel = format!("canonicalization.json rejection {id}");
        let wire = text(rejection, &rel, "text").unwrap();
        let pinned = text(rejection, &rel, "error_code").unwrap();
        let mapped = match json::parse(wire.as_bytes()) {
            Ok(_) => "parsed cleanly".to_owned(),
            Err(json::ParseError::NumberOutsideDomain { .. }) => {
                "envelope.schema_invalid".to_owned()
            }
            Err(_) => "envelope.malformed".to_owned(),
        };
        demand(
            &mut failures,
            format!("{rel}: mapped to {mapped}, pinned {pinned}"),
            mapped == pinned,
        );
    }

    assert!(
        failures.is_empty(),
        "{} rejection failures:\n  {}",
        failures.len(),
        failures.join("\n  ")
    );
}

/// `derivations.json` cases: every identity construction and every object
/// key re-derived from each case's own inputs equals the pinned expectation.
#[test]
fn derivation_cases_replay_every_identity_and_object_key() {
    let root = corpus_root();
    let table = load_json(&root, "derivations.json").unwrap();
    let cases = array(&table, "derivations.json", "cases").unwrap();
    let mut failures = Vec::new();

    for case in cases {
        let id = text(case, "derivations.json", "id").unwrap();
        let rel = format!("derivations.json case {id}");
        let inputs_value = member(case, &rel, "inputs").unwrap();
        let inputs = match IdentityInputs::from_derivation_case(inputs_value, &rel) {
            Ok(inputs) => inputs,
            Err(e) => {
                failures.push(e);
                continue;
            }
        };
        let expected = member(case, &rel, "expected").unwrap();
        assert_identity_block(&inputs, expected, &rel, &mut failures);
    }

    assert!(
        failures.is_empty(),
        "{} derivation failures:\n  {}",
        failures.len(),
        failures.join("\n  ")
    );
}

/// `derivations.json` preimages: the pinned framing bytes hash to the pinned
/// digest, the Rust derivations over the reference inputs produce the same
/// digest, and the `ingest-attempt-v1` preimage the signing-input builder
/// assembles is byte-identical to the pinned hex.
#[test]
fn pinned_preimages_hash_to_the_pinned_identities() {
    let root = corpus_root();
    let table = load_json(&root, "derivations.json").unwrap();
    let rel = "derivations.json";
    let preimages = member(&table, rel, "preimages").unwrap();
    let mut failures = Vec::new();

    // The labeled preimages correspond to the reference derivation case.
    let cases = array(&table, rel, "cases").unwrap();
    let reference = cases
        .iter()
        .find(|c| text(c, rel, "id").unwrap() == "ascii-baseline")
        .expect("the ascii-baseline reference case exists");
    let inputs_value = member(reference, rel, "inputs").unwrap();
    let inputs = IdentityInputs::from_derivation_case(inputs_value, rel).unwrap();
    let derived = derive(&inputs);

    for construction in [
        "session_hash",
        "artifact_hash",
        "occurrence_id",
        "attestation_id",
    ] {
        let block = member(preimages, rel, construction).unwrap();
        let label = text(block, rel, "label").unwrap();
        let pinned_hex = text(block, rel, "hex").unwrap();
        let pinned_sha = text(block, rel, "sha256").unwrap();
        let bytes = sha256::decode_hex(pinned_hex)
            .unwrap_or_else(|| panic!("{rel}: preimage {construction}: hex does not decode"));
        // The frame is the label, one 0x00, then length-prefixed fields.
        let head = [label.as_bytes(), &[0x00]].concat();
        demand(
            &mut failures,
            format!("{rel}: preimage {construction}: hex is not label+NUL framed"),
            bytes.starts_with(&head),
        );
        demand(
            &mut failures,
            format!(
                "{rel}: preimage {construction}: sha256 {pinned_sha} pinned, {} computed",
                sha256_hex(&bytes)
            ),
            sha256_hex(&bytes) == pinned_sha,
        );
        let computed = match construction {
            "session_hash" => derived.session.to_hex(),
            "artifact_hash" => derived.artifact.to_hex(),
            "occurrence_id" => derived.occurrence.to_hex(),
            _ => derived.attestation.to_hex(),
        };
        demand(
            &mut failures,
            format!(
                "{rel}: preimage {construction}: Rust derivation {computed}, preimage pins {pinned_sha}"
            ),
            computed == pinned_sha,
        );
    }

    // The signing preimage: byte-identical to what the crate assembles from
    // the reference scenario's own attempt record.
    let attempt_preimage = member(preimages, rel, "ingest_attempt_v1").unwrap();
    let pinned_hex = text(attempt_preimage, rel, "hex").unwrap();
    let (input, pinned_sha) = signing_input_of(&root, "valid-direct-baseline").unwrap();
    demand(
        &mut failures,
        format!(
            "{rel}: ingest-attempt-v1 preimage bytes disagree:\n    computed {}\n    pinned   {pinned_hex}",
            hex(&input)
        ),
        hex(&input) == pinned_hex,
    );
    demand(
        &mut failures,
        format!("{rel}: ingest-attempt-v1 preimage digest disagrees"),
        sha256_hex(&input) == pinned_sha,
    );

    assert!(
        failures.is_empty(),
        "{} preimage failures:\n  {}",
        failures.len(),
        failures.join("\n  ")
    );
}

/// Assemble the `ingest-attempt-v1` signing input from a scenario's attempt
/// record plus the digest of that preimage pinned in the manifest.
fn signing_input_of(root: &Path, scenario_id: &str) -> Result<(Vec<u8>, String), String> {
    let manifest = load_json(root, "manifest.json")?;
    let scenario = scenarios(&manifest)?
        .iter()
        .find(|s| text(s, "manifest.json", "id").unwrap() == scenario_id)
        .ok_or_else(|| format!("manifest.json: scenario {scenario_id} is missing"))?;
    let files = member(scenario, "manifest.json", "files")?;
    let attempt_rel = text(files, "manifest.json", "attempt")?;
    let attempt = load_json(root, attempt_rel)?;
    let input = signing_input_from_attempt(&attempt, attempt_rel)?;
    let pinned = text(
        member(scenario, "manifest.json", "signing")?,
        "manifest.json",
        "attempt_input_sha256",
    )?
    .to_owned();
    Ok((input, pinned))
}

/// Frame the signing input from one parsed attempt record.
fn signing_input_from_attempt(attempt: &Value, rel: &str) -> Result<Vec<u8>, String> {
    let content_type: ContentType = parsed(attempt, rel, "content_type")?;
    Ok(derivation::ingest_attempt_signing_input(
        text(attempt, rel, "http_method")?,
        text(attempt, rel, "route")?,
        content_type.as_str(),
        &parsed::<RequestContentDigest>(attempt, rel, "request_content_digest")?,
        &parsed::<EnvelopeDigest>(attempt, rel, "envelope_digest")?,
        &parsed::<BlobDigest>(attempt, rel, "payload_canonical_digest")?,
        &parsed::<IncomingChecksum>(attempt, rel, "payload_transport_digest")?,
        &parsed::<KeyId>(attempt, rel, "uploader_key_id")?,
        u63(attempt, rel, "authorization_epoch")?,
        &parsed::<Timestamp>(attempt, rel, "authorization_timestamp")?,
    ))
}

/// `keys.json`: every pinned public key derives its pinned key ID.
#[test]
fn keys_derive_their_pinned_key_ids() {
    let root = corpus_root();
    let table = load_json(&root, "keys.json").unwrap();
    let keys = array(&table, "keys.json", "keys").unwrap();
    let mut failures = Vec::new();

    for key in keys {
        let name = text(key, "keys.json", "name").unwrap();
        let rel = format!("keys.json key {name}");
        let public = Ed25519PublicKey::parse(text(key, &rel, "public_key").unwrap())
            .map_err(|_| format!("{rel}: public_key fails its grammar"))
            .unwrap();
        let computed = KeyId::from_public_key(&public).to_hex();
        let pinned = text(key, &rel, "key_id").unwrap();
        demand(
            &mut failures,
            format!("{rel}: key_id {computed} computed, {pinned} pinned"),
            computed == pinned,
        );
    }

    assert!(
        failures.is_empty(),
        "{} key-id failures:\n  {}",
        failures.len(),
        failures.join("\n  ")
    );
}

/// Every scenario: the envelope-validation outcome matches the pinned
/// expectation, and every identity and object key re-derived from the
/// envelope's own inputs equals the manifest's `identity` block — including
/// the envelopes the validator itself rejects, whose inputs still derive.
#[test]
fn scenarios_replay_envelope_outcomes_and_identities() {
    let root = corpus_root();
    let manifest = load_json(&root, "manifest.json").unwrap();
    let mut failures = Vec::new();

    for scenario in scenarios(&manifest).unwrap() {
        let id = text(scenario, "manifest.json", "id").unwrap();
        let rel = format!("scenario {id}");
        let files = member(scenario, &rel, "files").unwrap();
        let envelope_rel = text(files, &rel, "envelope").unwrap();
        let envelope_bytes = read(&root, envelope_rel).unwrap();

        // The identity block holds derivations of the envelope's own inputs
        // regardless of the validation outcome.
        let envelope_value = json::parse(&envelope_bytes)
            .map_err(|e| format!("{envelope_rel}: {e}"))
            .unwrap();
        let inputs = match IdentityInputs::from_envelope_value(&envelope_value, envelope_rel) {
            Ok(inputs) => inputs,
            Err(e) => {
                failures.push(e);
                continue;
            }
        };
        let identity = identity_block(scenario, id).unwrap();
        assert_identity_block(&inputs, identity, &rel, &mut failures);

        // The validation outcome: an `envelope.*` error code is this crate's
        // rejection; anything else fails in a later layer (auth, storage) and
        // the envelope itself must parse.
        let expect = member(scenario, &rel, "expect").unwrap();
        let expected_code = text_member(expect, "error_code");
        match Envelope::parse(&envelope_bytes) {
            Ok(envelope) => {
                if let Some(code) = expected_code
                    && code.starts_with("envelope.")
                {
                    failures.push(format!(
                        "{rel}: envelope parsed but {code} is pinned: {envelope:?}"
                    ));
                }
                // The typed envelope agrees with the raw-input derivations.
                demand(
                    &mut failures,
                    format!("{rel}: session hash disagrees with the identity block"),
                    envelope.rederive_session_hash().to_hex()
                        == text(identity, &rel, "session_hash").unwrap(),
                );
                demand(
                    &mut failures,
                    format!("{rel}: occurrence disagrees with the identity block"),
                    envelope.rederive_occurrence_id().to_hex()
                        == text(identity, &rel, "occurrence_id").unwrap(),
                );
                demand(
                    &mut failures,
                    format!("{rel}: attestation disagrees with the identity block"),
                    envelope.rederive_attestation_id().to_hex()
                        == text(identity, &rel, "attestation_id").unwrap(),
                );
                // Wire-canonical scenarios hold their exact bytes.
                if boolean(scenario, &rel, "envelope_wire_canonical").unwrap() {
                    demand(
                        &mut failures,
                        format!("{rel}: envelope file is not the canonical bytes"),
                        envelope.canonical_bytes() == envelope_bytes,
                    );
                }
            }
            Err(error) => match expected_code {
                Some(code) if code == error.code().as_str() => {}
                Some(code) => failures.push(format!(
                    "{rel}: envelope rejected as {}, {code} pinned",
                    error.code().as_str()
                )),
                None => failures.push(format!(
                    "{rel}: envelope rejected as {} but no envelope rejection is pinned",
                    error.code().as_str()
                )),
            },
        }
    }

    assert!(
        failures.is_empty(),
        "{} scenario identity failures:\n  {}",
        failures.len(),
        failures.join("\n  ")
    );
}

/// Every scenario's transmitted bytes and attempt record: the request-body
/// digest the signature covers, the payload coupling, the signing preimage
/// and its digest, and the error/receipt records' pinned shapes.
#[test]
fn scenarios_attempt_records_and_transmitted_bytes_replay() {
    let root = corpus_root();
    let manifest = load_json(&root, "manifest.json").unwrap();
    let mut failures = Vec::new();

    for scenario in scenarios(&manifest).unwrap() {
        let id = text(scenario, "manifest.json", "id").unwrap();
        let rel = format!("scenario {id}");
        let files = member(scenario, &rel, "files").unwrap();
        let attempt_rel = text(files, &rel, "attempt").unwrap().to_owned();
        let attempt = load_json(&root, &attempt_rel).unwrap();
        let body_rel = text(files, &rel, "request_body").unwrap();
        let body = read(&root, body_rel).unwrap();
        let signing = member(scenario, &rel, "signing").unwrap();
        let identity = identity_block(scenario, id).unwrap();

        // The covered request digest: over the pristine signed body. The two
        // in-transit tamper scenarios pin the pristine digest separately and
        // their transmitted body must genuinely differ from it.
        let covered = text(&attempt, &attempt_rel, "request_content_digest").unwrap();
        if let Some(pristine) = text_member(signing, "signed_body_sha256") {
            demand(
                &mut failures,
                format!("{rel}: covered digest {covered} != pinned pristine {pristine}"),
                covered == pristine,
            );
            demand(
                &mut failures,
                format!("{rel}: transmitted body equals the pristine signed body"),
                sha256_hex(&body) != covered,
            );
        } else {
            demand(
                &mut failures,
                format!(
                    "{rel}: request body digest {} computed, {covered} covered",
                    sha256_hex(&body)
                ),
                sha256_hex(&body) == covered,
            );
        }

        // Identity transport: the canonical and transported payload digests
        // agree and equal the occurrence's blob digest.
        let canonical = text(&attempt, &attempt_rel, "payload_canonical_digest").unwrap();
        let transported = text(&attempt, &rel, "payload_transport_digest").unwrap();
        demand(
            &mut failures,
            format!("{rel}: canonical and transported payload digests disagree"),
            canonical == transported,
        );
        demand(
            &mut failures,
            format!("{rel}: payload digest != identity blob_digest"),
            canonical == text(identity, &rel, "blob_digest").unwrap(),
        );
        // An untampered scenario's payload part hashes to the blob digest.
        if optional(signing, "signed_body_sha256").is_none() {
            let payload_rel = text(files, &rel, "payload").unwrap();
            let payload = read(&root, payload_rel).unwrap();
            demand(
                &mut failures,
                format!(
                    "{rel}: payload part digest {} computed, {canonical} pinned",
                    sha256_hex(&payload)
                ),
                sha256_hex(&payload) == canonical,
            );
        }

        // The envelope digest covers the envelope's canonical bytes.
        let envelope_rel = text(files, &rel, "envelope").unwrap();
        let envelope_value = load_json(&root, envelope_rel).unwrap();
        demand(
            &mut failures,
            format!("{rel}: envelope digest disagrees with canonical bytes"),
            sha256_hex(&envelope_value.canonical_bytes())
                == text(&attempt, &attempt_rel, "envelope_digest").unwrap(),
        );

        // The signing preimage and its digest.
        let input = signing_input_from_attempt(&attempt, &attempt_rel).unwrap();
        demand(
            &mut failures,
            format!("{rel}: signing input disagrees with the pinned preimage"),
            hex(&input) == text(signing, &rel, "attempt_input_hex").unwrap(),
        );
        demand(
            &mut failures,
            format!("{rel}: signing input digest disagrees"),
            sha256_hex(&input) == text(signing, &rel, "attempt_input_sha256").unwrap(),
        );

        // The error or receipt record matches the pinned expectation.
        let expect = member(scenario, &rel, "expect").unwrap();
        check_outcome_records(&root, expect, identity, &rel, files, &mut failures);
    }

    assert!(
        failures.is_empty(),
        "{} scenario byte failures:\n  {}",
        failures.len(),
        failures.join("\n  ")
    );
}

/// One scenario's error and receipt records: the error record's code and
/// retryability match the pinned expectation, and the receipt's identity and
/// outcome members agree with the manifest's identity block and outcomes.
fn check_outcome_records(
    root: &Path,
    expect: &Value,
    identity: &Value,
    rel: &str,
    files: &Value,
    failures: &mut Vec<String>,
) {
    if let Some(error_rel) = text_member(files, "error") {
        let error = load_json(root, error_rel).unwrap();
        demand(
            failures,
            format!("{rel}: error record code disagrees"),
            text(&error, error_rel, "code").unwrap() == text(expect, rel, "error_code").unwrap(),
        );
        demand(
            failures,
            format!("{rel}: error record retryability disagrees"),
            boolean(&error, error_rel, "retryable").unwrap()
                == boolean(expect, rel, "retryable").unwrap(),
        );
    }
    if let Some(receipt_rel) = text_member(files, "receipt") {
        let receipt = load_json(root, receipt_rel).unwrap();
        for field in [
            "occurrence_id",
            "attestation_id",
            "blob_digest",
            "blob_object_key",
            "occurrence_object_key",
            "attestation_object_key",
        ] {
            demand(
                failures,
                format!("{rel}: receipt {field} disagrees with the identity block"),
                text(&receipt, receipt_rel, field).unwrap() == text(identity, rel, field).unwrap(),
            );
        }
        if let Some(outcomes) = optional(expect, "outcomes") {
            for (outcome, member_name) in [
                ("attestation", "attestation_outcome"),
                ("blob", "blob_outcome"),
                ("occurrence", "occurrence_outcome"),
            ] {
                demand(
                    failures,
                    format!("{rel}: receipt {member_name} disagrees"),
                    text(&receipt, receipt_rel, member_name).unwrap()
                        == text(outcomes, rel, outcome).unwrap(),
                );
            }
        }
    }
}

/// One named scenario's envelope member, canonicalized for comparison.
/// `None` when the member is absent.
fn envelope_member_bytes(root: &Path, manifest: &Value, id: &str, field: &str) -> Option<Vec<u8>> {
    let scenario = scenarios(manifest)
        .unwrap()
        .iter()
        .find(|s| text(s, "manifest.json", "id").unwrap() == id)?;
    let files = member(scenario, "manifest.json", "files").unwrap();
    let envelope_rel = text(files, "manifest.json", "envelope").unwrap();
    let envelope = load_json(root, envelope_rel).unwrap();
    optional(&envelope, field).map(Value::canonical_bytes)
}

/// The manifest's cross-scenario invariants: relay convergence, cross-tenant
/// separation, and retry identity equality, checked against the identities
/// the manifest itself pins for the named scenarios.
#[test]
fn manifest_invariants_hold_across_their_scenarios() {
    let root = corpus_root();
    let manifest = load_json(&root, "manifest.json").unwrap();
    let invariants = member(&manifest, "manifest.json", "invariants").unwrap();
    let mut failures = Vec::new();

    let identity_of = |id: &str| -> Value {
        let scenario = scenarios(&manifest)
            .unwrap()
            .iter()
            .find(|s| text(s, "manifest.json", "id").unwrap() == id)
            .unwrap_or_else(|| panic!("manifest.json: scenario {id} is missing"));
        identity_block(scenario, id).unwrap().clone()
    };
    let scenario_ids = |invariant: &str| -> Vec<String> {
        array(
            member(invariants, "manifest.json", invariant).unwrap(),
            "manifest.json",
            "scenarios",
        )
        .unwrap()
        .iter()
        .map(|v| {
            let Value::Text(id) = v else {
                panic!("manifest.json: {invariant} scenario id is not a string");
            };
            id.clone()
        })
        .collect()
    };

    // One blob key and one occurrence key serve both uploaders, with two
    // attestation keys beside them (EC-05A, STO-013).
    let relay = member(invariants, "manifest.json", "relay_occurrence_equality").unwrap();
    let shared = member(relay, "manifest.json", "shared").unwrap();
    let pair = scenario_ids("relay_occurrence_equality");
    let direct = identity_of(&pair[0]);
    let relayed = identity_of(&pair[1]);
    for (identity, name) in [(&direct, "direct"), (&relayed, "relay")] {
        for field in ["blob_object_key", "occurrence_object_key"] {
            demand(
                &mut failures,
                format!("relay equality: {name} {field} is not the shared key"),
                text(identity, name, field).unwrap()
                    == text(shared, "manifest.json", field).unwrap(),
            );
        }
    }
    demand(
        &mut failures,
        "relay equality: relay attestation key is not the pinned one".to_owned(),
        text(&relayed, "relay", "attestation_object_key").unwrap()
            == text(shared, "manifest.json", "relay_attestation_object_key").unwrap(),
    );
    demand(
        &mut failures,
        "relay equality: both attestation keys are the same".to_owned(),
        text(&direct, "direct", "attestation_object_key").unwrap()
            != text(&relayed, "relay", "attestation_object_key").unwrap(),
    );

    // Tenant is the only changed identity input: session hashes diverge while
    // the blob digest is shared (EC-03, STO-002).
    let pair = scenario_ids("cross_tenant_separation");
    let first = identity_of(&pair[0]);
    let second = identity_of(&pair[1]);
    demand(
        &mut failures,
        "cross-tenant: session hashes are not distinct".to_owned(),
        text(&first, "first", "session_hash").unwrap()
            != text(&second, "second", "session_hash").unwrap(),
    );
    demand(
        &mut failures,
        "cross-tenant: blob digest is not shared".to_owned(),
        text(&first, "first", "blob_digest").unwrap()
            == text(&second, "second", "blob_digest").unwrap(),
    );

    // The frozen envelope across a retry (STO-004): a field named by
    // `identical_fields` compares from the identity block when present and
    // from the envelopes themselves otherwise (`request_id` is an envelope
    // member) — the rule the generator's --verify and the standalone
    // contract verifier both pin.
    let retry = member(invariants, "manifest.json", "retry_identity_equality").unwrap();
    let pair = scenario_ids("retry_identity_equality");
    let first = identity_of(&pair[0]);
    let second = identity_of(&pair[1]);
    for field in array(retry, "manifest.json", "identical_fields").unwrap() {
        let Value::Text(field) = field else {
            failures.push("manifest.json: retry identical_fields entry is not a string".into());
            continue;
        };
        let same = if optional(&first, field).is_some() {
            text(&first, "first", field).unwrap() == text(&second, "second", field).unwrap()
        } else {
            envelope_member_bytes(&root, &manifest, &pair[0], field).unwrap()
                == envelope_member_bytes(&root, &manifest, &pair[1], field).unwrap()
        };
        demand(
            &mut failures,
            format!("retry equality: {field} differs across the pair"),
            same,
        );
    }

    assert!(
        failures.is_empty(),
        "{} invariant failures:\n  {}",
        failures.len(),
        failures.join("\n  ")
    );
}
