// SPDX-License-Identifier: Apache-2.0

//! Replay of the usage-summary example corpus
//! (`schemas/v1/examples/usage-summaries`; plan Phase 10, token accounting).
//!
//! The corpus is generated by `tools/usagegen.py`, whose `--verify` (the
//! fast lane) owns byte-exact regeneration and JSON-Schema validation. This
//! file asserts the *Rust* side of the contract against the committed
//! bytes, using nothing but this crate's owned parser, canonicalizer,
//! digester, and derivation machinery — no new dependencies, the crate's
//! boundary rule — so the record shape is enforced where its producer (the
//! deterministic catalog rebuild) will be built:
//!
//! - every record is exactly its RFC 8785 canonical form plus one LF;
//! - every schema rule this crate can evaluate without a JSON Schema
//!   engine holds: required members, the closed shape, the reserved
//!   `not` block, the two-state `harness_usage` contract, the two-state
//!   `provider_usage` contract (the second, reserved denominator), the
//!   closed enums and bounded grammars;
//! - `usage_summary_digest` recomputes from each record's own canonical
//!   bytes with the pinned `usage-summary-v1` construction (VAL-005);
//! - the object key re-derives from the stored bytes and matches the
//!   manifest's pinned identity;
//! - every cited occurrence is one the raw-provenance bundle materializes
//!   (STO-012 traceability, cross-bundle);
//! - the manifest's byte counts and SHA-256 digests match the committed
//!   files, so the corpus cannot drift half-committed.

use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};

use archivist_protocol::derivation::FrameBuilder;
use archivist_protocol::json::{self, Object, Value};
use archivist_protocol::sha256;
use archivist_protocol::vocabulary::{AdapterId, TenantId, VersionToken};

/// The committed corpus, relative to this crate's manifest directory.
fn corpus_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../schemas/v1/examples/usage-summaries")
}

/// The family schema path.
fn schema_path() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../schemas/v1/usage-summary.json")
}

/// The shared vocabulary path.
fn common_schema_path() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../schemas/v1/common.json")
}

/// The exact-inference artifact schema the reserved denominator
/// reconciles with.
fn inference_schema_path() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../schemas/v1/inference-artifact.json")
}

/// The raw-provenance bundle whose occurrence IDs the corpus cites.
fn provenance_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../schemas/v1/examples/provenance/occurrences")
}

/// Read one file under `root`, failing with its repository-relative path.
fn read(root: impl AsRef<Path>, rel: &str) -> Result<Vec<u8>, String> {
    fs::read(root.as_ref().join(rel)).map_err(|e| format!("{rel}: {e}"))
}

/// Read and parse one JSON file under `root`.
fn load_json(root: impl AsRef<Path>, rel: &str) -> Result<Value, String> {
    json::parse(&read(root.as_ref(), rel)?).map_err(|e| format!("{rel}: {e}"))
}

fn as_object<'a>(value: &'a Value, what: &str) -> Result<&'a Object, String> {
    match value {
        Value::Object(object) => Ok(object),
        _ => Err(format!("{what}: expected an object")),
    }
}

fn text_of<'a>(value: &'a Value, what: &str) -> Result<&'a str, String> {
    match value {
        Value::Text(text) => Ok(text),
        _ => Err(format!("{what}: expected a string")),
    }
}

fn text_list(value: &Value, what: &str) -> Result<Vec<String>, String> {
    match value {
        Value::Array(items) => items
            .iter()
            .map(|item| text_of(item, what).map(str::to_owned))
            .collect(),
        _ => Err(format!("{what}: expected an array")),
    }
}

/// Collect a failure, so one run names everything that is wrong.
fn demand(failures: &mut Vec<String>, message: String, ok: bool) {
    if !ok {
        failures.push(message);
    }
}

/// The corpus's record entries from the manifest: path, byte count, digest.
fn manifest_entries(root: impl AsRef<Path>) -> Result<Vec<(String, usize, String)>, String> {
    let manifest = load_json(root.as_ref(), "manifest.json")?;
    let manifest = as_object(&manifest, "manifest.json")?;
    let Value::Array(files) = manifest
        .get("files")
        .ok_or("manifest.json: files is missing")?
    else {
        return Err("manifest.json: files must be an array".to_string());
    };
    files
        .iter()
        .map(|entry| {
            let entry = as_object(entry, "manifest files[]")?;
            let path = text_of(
                entry.get("path").ok_or("manifest files[]: path missing")?,
                "manifest files[].path",
            )?
            .to_owned();
            let bytes = match entry.get("bytes") {
                Some(Value::Int(bytes)) => usize::try_from(*bytes)
                    .map_err(|_| "manifest files[].bytes: expected a count".to_string())?,
                _ => return Err("manifest files[].bytes: expected a count".to_string()),
            };
            let sha = text_of(
                entry
                    .get("sha256")
                    .ok_or("manifest files[]: sha256 missing")?,
                "manifest files[].sha256",
            )?
            .to_owned();
            Ok((path, bytes, sha))
        })
        .collect()
}

/// The manifest's per-record identity objects, keyed by record path.
fn manifest_identities(root: impl AsRef<Path>) -> BTreeMap<String, Object> {
    let manifest = load_json(root.as_ref(), "manifest.json").expect("manifest.json parses");
    let manifest = as_object(&manifest, "manifest.json").expect("manifest is an object");
    let Some(Value::Array(files)) = manifest.get("files") else {
        panic!("manifest: files must be an array");
    };
    files
        .iter()
        .map(|entry| {
            let entry = as_object(entry, "manifest files[]").expect("manifest entry is an object");
            let path = text_of(
                entry.get("path").expect("manifest entry carries a path"),
                "manifest path",
            )
            .expect("manifest path is text")
            .to_owned();
            let identity = match entry.get("identity") {
                Some(identity) => as_object(identity, "manifest identity")
                    .expect("manifest identity is an object")
                    .clone(),
                None => panic!("manifest entry for {path} carries no identity"),
            };
            (path, identity)
        })
        .collect()
}

/// Every member name the schema defines — top level plus each `$defs`
/// object's properties and requireds — the set the committed records must
/// collectively exercise.
fn schema_member_names(schema: &Object) -> Vec<String> {
    let mut names: Vec<String> = Vec::new();
    let mut collect = |container: &Object| {
        if let Some(Value::Object(properties)) = container.get("properties") {
            names.extend(properties.iter().map(|(name, _)| name.to_owned()));
        }
        if let Some(required) = container.get("required") {
            names.extend(text_list(required, "schema required").unwrap_or_default());
        }
    };
    collect(schema);
    if let Some(Value::Object(defs)) = schema.get("$defs") {
        for (_, definition) in defs.iter() {
            if let Ok(definition) = as_object(definition, "$defs entry") {
                collect(definition);
            }
        }
    }
    names.sort();
    names.dedup();
    names
}

/// The reserved member names the schema rejects by name.
fn reserved_fields(schema: &Object) -> Vec<String> {
    schema
        .get("x-archivist")
        .and_then(|meta| as_object(meta, "x-archivist").ok())
        .and_then(|meta| meta.get("reservedFields"))
        .map(|reserved| text_list(reserved, "reservedFields").unwrap_or_default())
        .unwrap_or_default()
}

/// The domain label of the family's digest construction, read from the
/// schema's `x-archivist.derivations` — never hardcoded here.
fn digest_label(schema: &Object) -> Result<String, String> {
    let archivist = schema
        .get("x-archivist")
        .ok_or("schema: x-archivist metadata is missing")?;
    let derivations = as_object(archivist, "x-archivist")?
        .get("derivations")
        .ok_or("schema: x-archivist.derivations is missing")?;
    let Value::Array(derivations) = derivations else {
        return Err("schema: derivations must be an array".to_string());
    };
    let first = derivations
        .first()
        .ok_or("schema: derivations must not be empty")?;
    let derivation = as_object(first, "derivations[0]")?;
    text_of(
        derivation
            .get("label")
            .ok_or("derivations[0]: label missing")?,
        "derivations[0].label",
    )
    .map(str::to_owned)
}

/// The `model-id` grammar, equivalent to the schema's pattern: a bounded
/// ASCII token that cannot carry prose — no whitespace, no control
/// characters, at most 128 bytes.
fn model_id_valid(text: &str) -> bool {
    let mut chars = text.chars();
    if !matches!(chars.next(), Some(first) if first.is_ascii_alphanumeric()) {
        return false;
    }
    text.len() <= 128
        && chars
            .all(|c| c.is_ascii_alphanumeric() || matches!(c, '.' | '_' | ':' | '/' | '+' | '-'))
}

/// The shared `sha256-hex` shape: exactly 64 lowercase hex characters.
fn sha256_hex_valid(text: &str) -> bool {
    text.len() == 64
        && text
            .bytes()
            .all(|b| b.is_ascii_digit() || (b'a'..=b'f').contains(&b))
}

/// A non-negative integer count in the shared `u63` shape (the protocol's
/// integer domain is i64; the u63 cap excludes the sign bit).
fn count_valid(value: &Value) -> bool {
    matches!(value, Value::Int(count) if *count >= 0)
}

/// Every object key anywhere in the record, plus one failure per null.
fn walk_values(failures: &mut Vec<String>, rel: &str, value: &Value, out: &mut Vec<String>) {
    match value {
        Value::Null => failures.push(format!("{rel}: null where a member is omitted")),
        Value::Array(items) => {
            for item in items {
                walk_values(failures, rel, item, out);
            }
        }
        Value::Object(object) => {
            for (name, member) in object.iter() {
                out.push(name.to_owned());
                walk_values(failures, rel, member, out);
            }
        }
        _ => {}
    }
}

/// Required members present, the closed shape, and the reserved `not`
/// block: every member schema-defined, no reserved name anywhere at the
/// top level.
fn check_shape(
    failures: &mut Vec<String>,
    rel: &str,
    record: &Object,
    required: &[String],
    properties: &Object,
    reserved: &[String],
) {
    for name in required {
        if !record.contains(name) {
            failures.push(format!("{rel}: required member {name} is missing"));
        }
    }
    for (name, _) in record.iter() {
        demand(
            failures,
            format!("{rel}: member {name} is not schema-defined"),
            properties.contains(name),
        );
        demand(
            failures,
            format!("{rel}: reserved member {name} is present"),
            !reserved.iter().any(|reserved| reserved == name),
        );
    }
}

/// Scalar identity members against the wire grammars this crate owns.
fn check_identity(failures: &mut Vec<String>, rel: &str, record: &Object) {
    demand(
        failures,
        format!(
            "{rel}: usage_summary_version must be 1, got {:?}",
            record.get("usage_summary_version")
        ),
        matches!(record.get("usage_summary_version"), Some(Value::Int(1))),
    );
    for (name, grammar) in [
        ("tenant_id", "tenant"),
        ("adapter_id", "adapter"),
        ("pipeline_version", "version"),
        ("adapter_projection_version", "version"),
    ] {
        let Some(value) = record.get(name) else {
            continue; // `required` already reported the absence
        };
        let Ok(text) = text_of(value, &format!("{rel}.{name}")) else {
            failures.push(format!("{rel}: {name} must be text"));
            continue;
        };
        let ok = match grammar {
            "tenant" => TenantId::parse(text).is_ok(),
            "adapter" => AdapterId::parse(text).is_ok(),
            _ => VersionToken::parse(text).is_ok(),
        };
        demand(
            failures,
            format!("{rel}: {name} = {text:?} fails its wire grammar"),
            ok,
        );
    }
    for name in ["occurrence_id", "usage_summary_digest"] {
        let Some(value) = record.get(name) else {
            continue;
        };
        match text_of(value, &format!("{rel}.{name}")) {
            Ok(text) => demand(
                failures,
                format!("{rel}: {name} is not a sha256 hex digest"),
                sha256_hex_valid(text),
            ),
            Err(e) => failures.push(e),
        }
    }
    match record.get("pipeline_id") {
        Some(Value::Text(pipeline)) => demand(
            failures,
            format!("{rel}: pipeline_id {pipeline:?} is outside the closed v1 enum"),
            pipeline == "usage",
        ),
        other => failures.push(format!("{rel}: pipeline_id must be text, got {other:?}")),
    }
    for name in ["model_id", "service_tier"] {
        if let Some(value) = record.get(name) {
            match text_of(value, &format!("{rel}.{name}")) {
                Ok(text) => demand(
                    failures,
                    format!("{rel}: {name} = {text:?} fails the bounded model-id grammar"),
                    model_id_valid(text),
                ),
                Err(e) => failures.push(e),
            }
        }
    }
}

/// The object key re-derives from the stored bytes alone and agrees with
/// the manifest's pinned identity.
fn check_object_key(
    failures: &mut Vec<String>,
    rel: &str,
    record: &Object,
    identity: &Object,
    key_pattern: &str,
) {
    let (Some(Value::Text(digest)), Some(Value::Text(tenant)), Some(Value::Text(version))) = (
        record.get("usage_summary_digest"),
        record.get("tenant_id"),
        record.get("pipeline_version"),
    ) else {
        return; // reported by the shape and identity checks
    };
    let key = format!(
        "tenants/{tenant}/v1/derived/usage/{version}/usage-summaries/{}/{}.json",
        &digest[..2],
        digest
    );
    demand(
        failures,
        format!("{rel}: re-derived key violates the pinned derived layout"),
        key.starts_with(&format!(
            "tenants/{tenant}/v1/derived/usage/1/usage-summaries/"
        )) && Path::new(&key)
            .extension()
            .is_some_and(|ext| ext.eq_ignore_ascii_case("json")),
    );
    demand(
        failures,
        format!("{rel}: object-key shard must be the digest's first two hex"),
        key_pattern.contains("[0-9a-f]{2}") && key.contains(&format!("/{}/", &digest[..2])),
    );
    match identity.get("object_key") {
        Some(Value::Text(manifest_key)) => demand(
            failures,
            format!("{rel}: manifest object key disagrees with the re-derived key"),
            manifest_key == &key,
        ),
        other => failures.push(format!(
            "{rel}: manifest identity has no object key: {other:?}"
        )),
    }
}

/// The `measured` branch: every count required, at least one summed
/// message, both ephemeral classes and no others.
fn check_measured(failures: &mut Vec<String>, rel: &str, usage: &Object) {
    for name in [
        "input_tokens",
        "output_tokens",
        "cache_read_tokens",
        "reasoning_tokens",
    ] {
        match usage.get(name) {
            Some(value) if count_valid(value) => {}
            Some(Value::Int(count)) => {
                failures.push(format!("{rel}: {name} must be non-negative, got {count}"));
            }
            other => failures.push(format!("{rel}: {name} must be an integer, got {other:?}")),
        }
    }
    match usage.get("assistant_message_count") {
        Some(Value::Int(count)) if *count >= 1 => {}
        Some(Value::Int(count)) => failures.push(format!(
            "{rel}: measured usage must sum at least one assistant message, got {count}"
        )),
        other => failures.push(format!(
            "{rel}: assistant_message_count must be an integer, got {other:?}"
        )),
    }
    match usage.get("cache_creation") {
        Some(Value::Object(cache)) => {
            for class in ["ephemeral_5m", "ephemeral_1h"] {
                match cache.get(class) {
                    Some(value) if count_valid(value) => {}
                    Some(Value::Int(count)) => failures.push(format!(
                        "{rel}: cache_creation.{class} must be non-negative, got {count}"
                    )),
                    other => failures.push(format!(
                        "{rel}: cache_creation.{class} must be an integer, got {other:?}"
                    )),
                }
            }
            demand(
                failures,
                format!("{rel}: cache_creation must carry exactly the two closed classes"),
                cache.len() == 2,
            );
        }
        other => failures.push(format!(
            "{rel}: cache_creation must be an object, got {other:?}"
        )),
    }
}

/// The `unknown` branch: a closed reason and nothing else — no count may
/// sit beside an `unknown`.
fn check_unknown(failures: &mut Vec<String>, rel: &str, usage: &Object) {
    demand(
        failures,
        format!("{rel}: an unknown usage carries no count member at all"),
        usage.len() == 2,
    );
    match usage.get("reason") {
        Some(Value::Text(reason)) => demand(
            failures,
            format!("{rel}: unknown reason {reason:?} is outside the closed v1 set"),
            matches!(reason.as_str(), "absent" | "malformed" | "unsupported"),
        ),
        other => failures.push(format!("{rel}: unknown reason must be text, got {other:?}")),
    }
}

/// The provider denominator's `measured` branch: the artifact schema's
/// bounded intersection plus the report-count coverage denominator, in a
/// closed shape — nothing else fits, so no harness axis and no per-report
/// member can ride it.
fn check_provider_measured(failures: &mut Vec<String>, rel: &str, usage: &Object) {
    for name in ["input_tokens", "output_tokens", "total_tokens"] {
        match usage.get(name) {
            Some(value) if count_valid(value) => {}
            Some(Value::Int(count)) => {
                failures.push(format!(
                    "{rel}: provider_usage.{name} must be non-negative, got {count}"
                ));
            }
            other => failures.push(format!(
                "{rel}: provider_usage.{name} must be an integer, got {other:?}"
            )),
        }
    }
    match usage.get("usage_report_count") {
        Some(Value::Int(count)) if *count >= 1 => {}
        Some(Value::Int(count)) => failures.push(format!(
            "{rel}: measured provider usage must sum at least one usage report, got {count}"
        )),
        other => failures.push(format!(
            "{rel}: usage_report_count must be an integer, got {other:?}"
        )),
    }
    demand(
        failures,
        format!("{rel}: measured provider usage must carry exactly the closed counter set"),
        usage.len() == 5,
    );
}

/// The provider denominator's `unknown` branch: the refusal over the
/// closed reason set — covered traffic whose exact count does not exist,
/// never zeros and never silence.
fn check_provider_unknown(failures: &mut Vec<String>, rel: &str, usage: &Object) {
    demand(
        failures,
        format!("{rel}: an unknown provider usage carries no count member at all"),
        usage.len() == 2,
    );
    match usage.get("reason") {
        Some(Value::Text(reason)) => demand(
            failures,
            format!("{rel}: provider unknown reason {reason:?} is outside the closed v1 set"),
            matches!(reason.as_str(), "unreconciled" | "malformed"),
        ),
        other => failures.push(format!(
            "{rel}: provider unknown reason must be text, got {other:?}"
        )),
    }
}

#[test]
fn corpus_manifest_pins_the_committed_bytes() {
    let root = corpus_root();
    let mut failures = Vec::new();

    let entries = manifest_entries(&root).expect("manifest.json parses");
    demand(
        &mut failures,
        format!(
            "manifest: expected the eight scenario records, got {}",
            entries.len()
        ),
        entries.len() == 8,
    );
    for (rel, bytes, sha) in &entries {
        match read(&root, rel) {
            Ok(actual) => {
                demand(
                    &mut failures,
                    format!("{rel}: byte count drifted from the manifest"),
                    actual.len() == *bytes,
                );
                demand(
                    &mut failures,
                    format!("{rel}: sha256 drifted from the manifest"),
                    sha256::encode_hex(&sha256::digest(&actual)) == *sha,
                );
            }
            Err(e) => failures.push(e),
        }
    }

    // No stray files beside the manifest and the pinned records.
    let mut on_disk: Vec<String> = fs::read_dir(&root)
        .expect("the corpus directory is committed")
        .filter_map(std::result::Result::ok)
        .flat_map(|top| {
            let top = top.path();
            if top.is_dir() {
                fs::read_dir(&top)
                    .expect("corpus subdirectory reads")
                    .filter_map(std::result::Result::ok)
                    .map(|entry| {
                        top.file_name().unwrap().to_string_lossy().into_owned()
                            + "/"
                            + &entry.file_name().to_string_lossy()
                    })
                    .collect::<Vec<_>>()
            } else {
                vec![top.file_name().unwrap().to_string_lossy().into_owned()]
            }
        })
        .collect();
    on_disk.sort();
    let mut expected: Vec<String> = entries.iter().map(|(rel, _, _)| rel.clone()).collect();
    expected.push("manifest.json".to_string());
    expected.sort();
    demand(
        &mut failures,
        format!("corpus directory contents drifted from the manifest: {on_disk:?}"),
        on_disk == expected,
    );

    assert!(failures.is_empty(), "{}", failures.join("\n"));
}

#[test]
fn records_are_canonical_closed_and_schema_shaped() {
    let root = corpus_root();
    let schema = load_json(
        schema_path().parent().unwrap(),
        schema_path().file_name().unwrap().to_str().unwrap(),
    )
    .expect("usage-summary.json parses");
    let schema = as_object(&schema, "usage-summary.json").expect("schema is an object");
    let common = load_json(
        common_schema_path().parent().unwrap(),
        common_schema_path().file_name().unwrap().to_str().unwrap(),
    )
    .expect("common.json parses");
    let common = as_object(&common, "common.json").expect("common.json is an object");

    let required = text_list(
        schema
            .get("required")
            .expect("schema pins required members"),
        "schema required",
    )
    .expect("schema required is a string array");
    let properties = match schema.get("properties") {
        Some(Value::Object(properties)) => properties.clone(),
        _ => panic!("schema: properties must be an object"),
    };
    let reserved = reserved_fields(schema);
    assert!(
        !reserved.is_empty(),
        "schema: reserved list must not be empty"
    );
    let key_pattern = common
        .get("$defs")
        .and_then(|defs| as_object(defs, "common.json $defs").ok())
        .and_then(|defs| defs.get("usage-summary-object-key"))
        .and_then(|shape| as_object(shape, "usage-summary-object-key").ok())
        .and_then(|shape| shape.get("pattern"))
        .and_then(|pattern| text_of(pattern, "usage-summary-object-key.pattern").ok())
        .map(str::to_owned)
        .expect("common.json owns the usage-summary-object-key pattern");

    let identities = manifest_identities(&root);
    let entries = manifest_entries(&root).expect("manifest.json parses");
    let mut failures = Vec::new();
    let mut exercised: Vec<String> = Vec::new();

    for (rel, _, _) in entries {
        let Ok(raw) = read(&root, &rel) else {
            continue; // the manifest test reports the missing file
        };
        let parsed = match json::parse(&raw) {
            Ok(value) => value,
            Err(e) => {
                failures.push(format!("{rel}: {e}"));
                continue;
            }
        };

        // Canonical serialization: the file is exactly the canonical bytes
        // plus one trailing LF.
        let mut canonical = parsed.canonical_bytes();
        canonical.push(b'\n');
        demand(
            &mut failures,
            format!("{rel}: file is not its canonical rendering plus one LF"),
            canonical == raw,
        );

        let Ok(record) = as_object(&parsed, &rel) else {
            failures.push(format!("{rel}: record must be an object"));
            continue;
        };
        check_shape(
            &mut failures,
            &rel,
            record,
            &required,
            &properties,
            &reserved,
        );
        check_identity(&mut failures, &rel, record);
        walk_values(&mut failures, &rel, &parsed, &mut exercised);
        check_object_key(&mut failures, &rel, record, &identities[&rel], &key_pattern);
    }

    // The committed records collectively exercise every member the schema
    // defines — required and optional, measured and unknown, both
    // ephemeral classes.
    exercised.sort();
    exercised.dedup();
    for name in schema_member_names(schema) {
        demand(
            &mut failures,
            format!("corpus: schema member {name} is never exercised by any record"),
            exercised.iter().any(|seen| seen == &name),
        );
    }

    assert!(failures.is_empty(), "{}", failures.join("\n"));
}

#[test]
fn harness_usage_follows_the_two_state_contract() {
    let root = corpus_root();
    let mut failures = Vec::new();

    let mut measured_records = 0usize;
    let mut unknown_records = 0usize;
    let mut digests: Vec<String> = Vec::new();

    for (rel, _, _) in manifest_entries(&root).expect("manifest.json parses") {
        let parsed = load_json(&root, &rel).expect("record parses");
        let record = as_object(&parsed, &rel).expect("record is an object");
        match record.get("usage_summary_digest") {
            Some(Value::Text(digest)) => digests.push(digest.clone()),
            other => {
                failures.push(format!(
                    "{rel}: usage_summary_digest must be text, got {other:?}"
                ));
            }
        }

        let Some(usage) = record.get("harness_usage") else {
            failures.push(format!(
                "{rel}: harness_usage is missing — the bounded state is mandatory"
            ));
            continue;
        };
        let Ok(usage) = as_object(usage, &format!("{rel}.harness_usage")) else {
            failures.push(format!("{rel}: harness_usage must be an object"));
            continue;
        };
        match usage.get("state") {
            Some(Value::Text(state)) if state == "measured" => {
                measured_records += 1;
                check_measured(&mut failures, &rel, usage);
            }
            Some(Value::Text(state)) if state == "unknown" => {
                unknown_records += 1;
                check_unknown(&mut failures, &rel, usage);
            }
            other => failures.push(format!(
                "{rel}: harness_usage.state must be measured or unknown, got {other:?}"
            )),
        }
    }

    // The corpus pins both states and pairwise-distinct identities.
    demand(
        &mut failures,
        format!(
            "corpus: expected measured and unknown fixtures, got {measured_records} measured / {unknown_records} unknown"
        ),
        measured_records >= 1 && unknown_records >= 1,
    );
    let mut distinct = digests.clone();
    distinct.sort();
    distinct.dedup();
    demand(
        &mut failures,
        "corpus: usage summary digests must be pairwise distinct".to_string(),
        distinct.len() == digests.len(),
    );

    assert!(failures.is_empty(), "{}", failures.join("\n"));
}

/// The reserved provider-observed denominator's own two-state contract:
/// every record's `provider_usage` is either absent (outside capture
/// coverage) or a well-formed measured/unknown object over its own
/// members, and the corpus pins every cell of the both/either/neither
/// coverage matrix — a row may carry both, either, or neither.
#[test]
fn provider_usage_follows_its_own_two_state_contract() {
    let root = corpus_root();
    let mut failures = Vec::new();

    let mut both_measured = 0usize;
    let mut harness_only = 0usize;
    let mut provider_only = 0usize;
    let mut neither_measured = 0usize;
    let mut provider_unknown = 0usize;
    let mut provider_absent = 0usize;

    for (rel, _, _) in manifest_entries(&root).expect("manifest.json parses") {
        let parsed = load_json(&root, &rel).expect("record parses");
        let record = as_object(&parsed, &rel).expect("record is an object");
        let harness_measured = matches!(
            record.get("harness_usage"),
            Some(Value::Object(usage)) if usage.get("state")
                == Some(&Value::Text("measured".to_owned()))
        );
        // Absence is itself the third coverage state — outside exact
        // capture entirely — and counts as not measured in the matrix.
        let provider_measured = match record.get("provider_usage") {
            None => {
                provider_absent += 1;
                false
            }
            Some(Value::Object(usage)) => match usage.get("state") {
                Some(Value::Text(state)) if state == "measured" => {
                    check_provider_measured(&mut failures, &rel, usage);
                    true
                }
                Some(Value::Text(state)) if state == "unknown" => {
                    provider_unknown += 1;
                    check_provider_unknown(&mut failures, &rel, usage);
                    false
                }
                other => {
                    failures.push(format!(
                        "{rel}: provider_usage.state must be measured or unknown, got {other:?}"
                    ));
                    false
                }
            },
            other => {
                failures.push(format!(
                    "{rel}: provider_usage must be an object when present, got {other:?}"
                ));
                false
            }
        };
        if provider_measured && harness_measured {
            both_measured += 1;
        } else if provider_measured {
            provider_only += 1;
        } else if harness_measured {
            harness_only += 1;
        } else {
            neither_measured += 1;
        }
    }

    // Every cell of the plan's both/either/neither matrix is populated.
    for (cell, count) in [
        ("both denominators measured", both_measured),
        ("only the harness denominator measured", harness_only),
        ("only the provider denominator measured", provider_only),
        ("neither denominator measured", neither_measured),
        ("provider denominator unknown", provider_unknown),
        ("provider member absent", provider_absent),
    ] {
        demand(
            &mut failures,
            format!("corpus: the {cell} cell is empty — every coverage outcome must be pinned"),
            count >= 1,
        );
    }

    assert!(failures.is_empty(), "{}", failures.join("\n"));
}

/// The two denominators cannot be expressed as one member: they are two
/// distinct schema properties with distinct `$defs` shapes, each closed
/// over its own axes, the provider member reserved (optional) while the
/// harness member is required, and the grand-total and artifact-counter
/// names reserved at the root so nothing can sum or hoist the two into
/// one member.
#[test]
#[allow(clippy::too_many_lines)]
fn the_two_denominators_are_separate_members() {
    let schema = load_json(
        schema_path().parent().unwrap(),
        schema_path().file_name().unwrap().to_str().unwrap(),
    )
    .expect("usage-summary.json parses");
    let schema = as_object(&schema, "usage-summary.json").expect("schema is an object");
    let mut failures = Vec::new();

    let Some(Value::Object(properties)) = schema.get("properties") else {
        panic!("schema: properties must be an object");
    };
    let usage_members: Vec<&str> = properties
        .iter()
        .filter(|(name, _)| name.ends_with("_usage"))
        .map(|(name, _)| name)
        .collect();
    demand(
        &mut failures,
        format!("schema: exactly two usage-denominator members must exist, got {usage_members:?}"),
        usage_members.len() == 2
            && usage_members.contains(&"harness_usage")
            && usage_members.contains(&"provider_usage"),
    );

    // The harness member is required; the provider member is reserved —
    // optional until the Phase 9 producer ships, never folded into the
    // required set.
    let required = text_list(
        schema
            .get("required")
            .expect("schema pins required members"),
        "schema required",
    )
    .expect("schema required is a string array");
    demand(
        &mut failures,
        "schema: harness_usage must stay required".to_string(),
        required.iter().any(|name| name == "harness_usage"),
    );
    demand(
        &mut failures,
        "schema: the reserved provider_usage must stay optional in v1".to_string(),
        !required.iter().any(|name| name == "provider_usage"),
    );
    // The reservation is declared, not incidental: the provider member
    // carries the optional-additive compat bearing, so tooling reads the
    // reservation from the schema's own metadata instead of inferring it
    // from the required list's silence.
    let provider_compat = properties
        .get("provider_usage")
        .and_then(|meta| as_object(meta, "properties.provider_usage").ok())
        .and_then(|meta| meta.get("x-archivist"))
        .and_then(|meta| as_object(meta, "x-archivist").ok())
        .and_then(|meta| meta.get("compat"));
    demand(
        &mut failures,
        "schema: the reserved provider_usage must declare the \
         optional-additive-v1 compat bearing"
            .to_string(),
        provider_compat == Some(&Value::Text("optional-additive-v1".to_owned())),
    );

    // Each denominator's measured object is closed over its own axes:
    // `input_tokens`/`output_tokens` are shared axis names inside two
    // different members; the axes unique to one denominator must not leak
    // into the other's object.
    let Some(Value::Object(defs)) = schema.get("$defs") else {
        panic!("schema: $defs must be an object");
    };
    let measured_shapes = ["harness-usage-measured", "provider-usage-measured"];
    let mut shapes = std::collections::BTreeMap::new();
    for def in measured_shapes {
        let shape = defs
            .get(def)
            .and_then(|shape| as_object(shape, def).ok())
            .unwrap_or_else(|| panic!("schema: ${def} must exist"));
        let Some(Value::Object(props)) = shape.get("properties") else {
            panic!("schema: {def}.properties must be an object");
        };
        shapes.insert(def, props.clone());
        demand(
            &mut failures,
            format!("schema: {def} must be the closed shape (additionalProperties false)"),
            shape.get("additionalProperties") == Some(&Value::Bool(false)),
        );
    }
    let harness_axes: Vec<String> = shapes["harness-usage-measured"]
        .iter()
        .map(|(name, _)| name.to_owned())
        .collect();
    let provider_axes: Vec<String> = shapes["provider-usage-measured"]
        .iter()
        .map(|(name, _)| name.to_owned())
        .collect();
    for axis in ["total_tokens", "usage_report_count", "usage_source"] {
        demand(
            &mut failures,
            format!("schema: the harness denominator cannot carry the provider axis {axis}"),
            !harness_axes.iter().any(|name| name == axis),
        );
    }
    for axis in [
        "cache_read_tokens",
        "cache_creation",
        "reasoning_tokens",
        "assistant_message_count",
    ] {
        demand(
            &mut failures,
            format!("schema: the provider denominator cannot carry the harness axis {axis}"),
            !provider_axes.iter().any(|name| name == axis),
        );
    }

    // The refusal shapes are separate too: two closed reason enums, one
    // per denominator, each in its own object.
    for (def, reasons) in [
        (
            "harness-usage-unknown",
            vec!["absent", "malformed", "unsupported"],
        ),
        ("provider-usage-unknown", vec!["unreconciled", "malformed"]),
    ] {
        let shape = defs
            .get(def)
            .and_then(|shape| as_object(shape, def).ok())
            .unwrap_or_else(|| panic!("schema: ${def} must exist"));
        let Some(Value::Object(props)) = shape.get("properties") else {
            panic!("schema: {def}.properties must be an object");
        };
        let Some(Value::Object(reason)) = props.get("reason") else {
            panic!("schema: {def}.reason must be an object");
        };
        let tokens = text_list(
            reason
                .get("enum")
                .unwrap_or_else(|| panic!("schema: {def}.reason.enum")),
            "reason enum",
        )
        .expect("reason enum is a string array");
        demand(
            &mut failures,
            format!("schema: {def}.reason must be the closed set {reasons:?}"),
            tokens == reasons,
        );
    }

    // The grand-total names and the artifact schema's own counter names
    // are reserved at the root, and the `not` block rejects exactly the
    // reserved set — nothing at the top level can sum the denominators
    // into one member or hoist the artifact's payload into the row.
    let reserved = reserved_fields(schema);
    for name in [
        "aggregate_tokens",
        "combined_tokens",
        "summed_tokens",
        "total_tokens",
        "usage_input_tokens",
        "usage_output_tokens",
        "usage_total_tokens",
    ] {
        demand(
            &mut failures,
            format!("schema: {name} must be reserved at the root"),
            reserved.iter().any(|reserved| reserved == name),
        );
    }
    let Some(Value::Object(not)) = schema.get("not") else {
        panic!("schema: the not block must exist");
    };
    let Some(Value::Array(any_of)) = not.get("anyOf") else {
        panic!("schema: the not block must carry anyOf");
    };
    let rejected: Vec<String> = any_of
        .iter()
        .filter_map(|entry| as_object(entry, "not.anyOf entry").ok())
        .filter(|entry| entry.len() == 1 && entry.contains("required"))
        .filter_map(|entry| {
            text_list(
                entry
                    .get("required")
                    .expect("the required key was just checked"),
                "not.anyOf required",
            )
            .ok()
        })
        .flatten()
        .collect();
    let mut sorted_reserved = reserved.clone();
    sorted_reserved.sort();
    let mut sorted_rejected = rejected.clone();
    sorted_rejected.sort();
    demand(
        &mut failures,
        "schema: the not block must reject exactly the reserved set".to_string(),
        sorted_reserved == sorted_rejected,
    );

    assert!(failures.is_empty(), "{}", failures.join("\n"));
}

/// The reserved provider-observed denominator reconciles with the
/// exact-inference artifact schema's own definition (aa-b5cf6541): the
/// `usage` artifact kind's required counters — read from
/// inference-artifact.json itself, never restated here — map member for
/// member onto `provider-usage-measured`, on the same shared u63 domain,
/// with the artifact's per-report `usage_source` deliberately absent from
/// the per-occurrence aggregate.
#[test]
#[allow(clippy::too_many_lines)]
fn provider_usage_reconciles_with_the_inference_artifact_schema() {
    let schema = load_json(
        schema_path().parent().unwrap(),
        schema_path().file_name().unwrap().to_str().unwrap(),
    )
    .expect("usage-summary.json parses");
    let schema = as_object(&schema, "usage-summary.json").expect("schema is an object");
    let artifact = load_json(
        inference_schema_path().parent().unwrap(),
        inference_schema_path()
            .file_name()
            .unwrap()
            .to_str()
            .unwrap(),
    )
    .expect("inference-artifact.json parses");
    let artifact =
        as_object(&artifact, "inference-artifact.json").expect("artifact schema is an object");
    let mut failures = Vec::new();

    // The artifact side: the `usage` kind's own definition.
    let Some(Value::Array(all_of)) = artifact.get("allOf") else {
        panic!("inference-artifact.json: allOf must be an array");
    };
    let usage_branch = all_of
        .iter()
        .filter_map(|branch| as_object(branch, "allOf entry").ok())
        .find(|branch| {
            branch
                .get("if")
                .and_then(|cond| as_object(cond, "if").ok())
                .and_then(|cond| cond.get("properties"))
                .and_then(|props| as_object(props, "if.properties").ok())
                .and_then(|props| props.get("artifact_kind"))
                .and_then(|kind| as_object(kind, "artifact_kind").ok())
                .and_then(|kind| kind.get("const"))
                == Some(&Value::Text("usage".to_owned()))
        })
        .expect("inference-artifact.json: the usage-kind branch exists");
    let then = as_object(
        usage_branch
            .get("then")
            .expect("the usage branch carries a then"),
        "then",
    )
    .expect("then is an object");
    let artifact_required = text_list(
        then.get("required")
            .expect("the usage kind requires members"),
        "usage-kind required",
    )
    .expect("usage-kind required is a string array");
    for member in ["metadata", "usage_source"] {
        demand(
            &mut failures,
            format!("artifact: the usage kind must require {member}"),
            artifact_required.iter().any(|name| name == member),
        );
    }
    let metadata_required = then
        .get("properties")
        .and_then(|props| as_object(props, "then.properties").ok())
        .and_then(|props| props.get("metadata"))
        .and_then(|shape| as_object(shape, "metadata").ok())
        .and_then(|shape| shape.get("required"))
        .map(|required| text_list(required, "metadata required").expect("a string array"))
        .unwrap_or_default();
    // The counter mapping this reconciliation pins: the artifact's own
    // counter names onto the summary member names.
    let counter_map = [
        ("input_tokens", "usage_input_tokens"),
        ("output_tokens", "usage_output_tokens"),
        ("total_tokens", "usage_total_tokens"),
    ];
    for (_, theirs) in counter_map {
        demand(
            &mut failures,
            format!(
                "artifact: the usage kind's counter set must include {theirs} (bounded intersection)"
            ),
            metadata_required.iter().any(|name| name == theirs),
        );
    }
    let artifact_metadata_props = artifact
        .get("properties")
        .and_then(|props| as_object(props, "properties").ok())
        .and_then(|props| props.get("metadata"))
        .and_then(|shape| as_object(shape, "metadata").ok())
        .and_then(|shape| shape.get("properties"))
        .and_then(|props| as_object(props, "metadata.properties").ok())
        .expect("the metadata allowlist carries properties");
    for (_, theirs) in counter_map {
        let counter = artifact_metadata_props
            .get(theirs)
            .and_then(|shape| as_object(shape, theirs).ok())
            .unwrap_or_else(|| panic!("artifact: {theirs} must exist"));
        demand(
            &mut failures,
            format!("artifact: {theirs} must stay the shared u63 counter"),
            counter.get("$ref")
                == Some(&Value::Text(
                    "urn:agent-archivist:schema:v1:common#/$defs/u63".to_owned(),
                )),
        );
    }

    // The summary side: the measured provider denominator carries exactly
    // the mapped counters plus its state and report count, all u63, in a
    // closed shape — and no per-report source member.
    let Some(Value::Object(defs)) = schema.get("$defs") else {
        panic!("schema: $defs must be an object");
    };
    let measured = as_object(
        defs.get("provider-usage-measured")
            .expect("provider-usage-measured exists"),
        "provider-usage-measured",
    )
    .expect("provider-usage-measured is an object");
    let Some(Value::Object(props)) = measured.get("properties") else {
        panic!("schema: provider-usage-measured.properties must be an object");
    };
    let required = text_list(
        measured
            .get("required")
            .expect("provider-usage-measured pins requireds"),
        "provider-usage-measured required",
    )
    .expect("a string array");
    for (ours, _) in counter_map {
        demand(
            &mut failures,
            format!("schema: the provider denominator must require {ours}"),
            required.iter().any(|name| name == ours),
        );
        demand(
            &mut failures,
            format!("schema: the provider counter {ours} must stay the shared u63"),
            props
                .get(ours)
                .and_then(|shape| as_object(shape, ours).ok())
                .and_then(|shape| shape.get("$ref"))
                == Some(&Value::Text(
                    "urn:agent-archivist:schema:v1:common#/$defs/u63".to_owned(),
                )),
        );
    }
    demand(
        &mut failures,
        "schema: the measured provider denominator must require the report-count coverage denominator"
            .to_string(),
        required.iter().any(|name| name == "usage_report_count"),
    );
    demand(
        &mut failures,
        "schema: the artifact's per-report usage_source cannot ride the per-occurrence aggregate"
            .to_string(),
        !props.contains("usage_source"),
    );
    demand(
        &mut failures,
        "schema: the provider denominator must be the closed counter shape".to_string(),
        props.len() == 5,
    );

    assert!(failures.is_empty(), "{}", failures.join("\n"));
}

#[test]
fn digests_recompute_with_the_pinned_construction() {
    let schema = load_json(
        schema_path().parent().unwrap(),
        schema_path().file_name().unwrap().to_str().unwrap(),
    )
    .expect("usage-summary.json parses");
    let label =
        digest_label(as_object(&schema, "usage-summary.json").expect("schema is an object"))
            .expect("schema pins a digest construction");
    assert_eq!(
        label, "usage-summary-v1",
        "the schema must pin the usage-summary-v1 construction"
    );

    let root = corpus_root();
    for (rel, _, _) in manifest_entries(&root).expect("manifest.json parses") {
        let parsed = load_json(&root, &rel).expect("record parses");
        let mut record = as_object(&parsed, &rel)
            .expect("record is an object")
            .clone();
        let Some(Value::Text(committed)) = record.remove("usage_summary_digest") else {
            panic!("{rel}: usage_summary_digest must be text");
        };
        // Construction `usage-summary-v1` (VAL-005 self-verification): the
        // labeled frame over the record's own canonical bytes with the
        // digest member removed.
        let mut builder = FrameBuilder::new(&label);
        builder.push_bytes(&Value::Object(record).canonical_bytes());
        let frame = builder.finish();
        assert_eq!(
            sha256::encode_hex(&frame),
            committed,
            "{rel}: usage_summary_digest is not the {label} digest of the record's own canonical bytes"
        );
    }
}

#[test]
fn citations_name_provenance_bundle_occurrences() {
    let mut failures = Vec::new();

    let mut manifests: Vec<String> = fs::read_dir(provenance_root())
        .expect("the raw-provenance bundle must be committed beside this corpus")
        .filter_map(std::result::Result::ok)
        .map(|entry| entry.file_name().to_string_lossy().into_owned())
        .filter(|name| {
            Path::new(name)
                .extension()
                .is_some_and(|ext| ext.eq_ignore_ascii_case("json"))
        })
        .collect();
    manifests.sort();
    assert!(
        !manifests.is_empty(),
        "the provenance bundle lists no occurrences"
    );

    let mut provenance: Vec<String> = Vec::new();
    for rel in &manifests {
        match load_json(provenance_root(), rel) {
            Ok(value) => {
                let manifest =
                    as_object(&value, "occurrence manifest").expect("manifest is an object");
                match manifest.get("occurrence_id") {
                    Some(Value::Text(id)) => provenance.push(id.clone()),
                    other => {
                        failures.push(format!("{rel}: occurrence_id must be text, got {other:?}"));
                    }
                }
            }
            Err(e) => failures.push(e),
        }
    }

    let root = corpus_root();
    for (rel, _, _) in manifest_entries(&root).expect("manifest.json parses") {
        let parsed = load_json(&root, &rel).expect("record parses");
        let record = as_object(&parsed, &rel).expect("record is an object");
        match record.get("occurrence_id") {
            Some(Value::Text(occurrence)) => demand(
                &mut failures,
                format!(
                    "{rel}: cites occurrence {occurrence}, which the provenance bundle does not materialize"
                ),
                provenance.iter().any(|known| known == occurrence),
            ),
            other => failures.push(format!("{rel}: occurrence_id must be text, got {other:?}")),
        }
    }

    assert!(failures.is_empty(), "{}", failures.join("\n"));
}
