// SPDX-License-Identifier: Apache-2.0

//! Replay of the usage-summary example corpus
//! (`schemas/v1/examples/usage-summaries`; plan Phase 10, token accounting).
//!
//! The corpus is generated by `tools/usagegen.py`, whose `--verify` (the
//! fast lane) owns byte-exact regeneration and JSON-Schema validation. This
//! file asserts the *Rust* side of the contract against the committed
//! bytes, using nothing but this crate's owned parser, canonicalizer,
//! digester, and derivation machinery — no new dependencies, the crate's
//! boundary rule — so the record shape is enforced where its producer (the
//! deterministic catalog rebuild) will be built:
//!
//! - every record is exactly its RFC 8785 canonical form plus one LF;
//! - every schema rule this crate can evaluate without a JSON Schema
//!   engine holds: required members, the closed shape, the reserved
//!   `not` block, the two-state `harness_usage` contract, the closed enums
//!   and bounded grammars;
//! - `usage_summary_digest` recomputes from each record's own canonical
//!   bytes with the pinned `usage-summary-v1` construction (VAL-005);
//! - the object key re-derives from the stored bytes and matches the
//!   manifest's pinned identity;
//! - every cited occurrence is one the raw-provenance bundle materializes
//!   (STO-012 traceability, cross-bundle);
//! - the manifest's byte counts and SHA-256 digests match the committed
//!   files, so the corpus cannot drift half-committed.

use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};

use archivist_protocol::derivation::FrameBuilder;
use archivist_protocol::json::{self, Object, Value};
use archivist_protocol::sha256;
use archivist_protocol::vocabulary::{AdapterId, TenantId, VersionToken};

/// The committed corpus, relative to this crate's manifest directory.
fn corpus_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../schemas/v1/examples/usage-summaries")
}

/// The family schema path.
fn schema_path() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../schemas/v1/usage-summary.json")
}

/// The shared vocabulary path.
fn common_schema_path() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../schemas/v1/common.json")
}

/// The raw-provenance bundle whose occurrence IDs the corpus cites.
fn provenance_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../schemas/v1/examples/provenance/occurrences")
}

/// Read one file under `root`, failing with its repository-relative path.
fn read(root: impl AsRef<Path>, rel: &str) -> Result<Vec<u8>, String> {
    fs::read(root.as_ref().join(rel)).map_err(|e| format!("{rel}: {e}"))
}

/// Read and parse one JSON file under `root`.
fn load_json(root: impl AsRef<Path>, rel: &str) -> Result<Value, String> {
    json::parse(&read(root.as_ref(), rel)?).map_err(|e| format!("{rel}: {e}"))
}

fn as_object<'a>(value: &'a Value, what: &str) -> Result<&'a Object, String> {
    match value {
        Value::Object(object) => Ok(object),
        _ => Err(format!("{what}: expected an object")),
    }
}

fn text_of<'a>(value: &'a Value, what: &str) -> Result<&'a str, String> {
    match value {
        Value::Text(text) => Ok(text),
        _ => Err(format!("{what}: expected a string")),
    }
}

fn text_list(value: &Value, what: &str) -> Result<Vec<String>, String> {
    match value {
        Value::Array(items) => items
            .iter()
            .map(|item| text_of(item, what).map(str::to_owned))
            .collect(),
        _ => Err(format!("{what}: expected an array")),
    }
}

/// Collect a failure, so one run names everything that is wrong.
fn demand(failures: &mut Vec<String>, message: String, ok: bool) {
    if !ok {
        failures.push(message);
    }
}

/// The corpus's record entries from the manifest: path, byte count, digest.
fn manifest_entries(root: impl AsRef<Path>) -> Result<Vec<(String, usize, String)>, String> {
    let manifest = load_json(root.as_ref(), "manifest.json")?;
    let manifest = as_object(&manifest, "manifest.json")?;
    let Value::Array(files) = manifest
        .get("files")
        .ok_or("manifest.json: files is missing")?
    else {
        return Err("manifest.json: files must be an array".to_string());
    };
    files
        .iter()
        .map(|entry| {
            let entry = as_object(entry, "manifest files[]")?;
            let path = text_of(
                entry.get("path").ok_or("manifest files[]: path missing")?,
                "manifest files[].path",
            )?
            .to_owned();
            let bytes = match entry.get("bytes") {
                Some(Value::Int(bytes)) => usize::try_from(*bytes)
                    .map_err(|_| "manifest files[].bytes: expected a count".to_string())?,
                _ => return Err("manifest files[].bytes: expected a count".to_string()),
            };
            let sha = text_of(
                entry
                    .get("sha256")
                    .ok_or("manifest files[]: sha256 missing")?,
                "manifest files[].sha256",
            )?
            .to_owned();
            Ok((path, bytes, sha))
        })
        .collect()
}

/// The manifest's per-record identity objects, keyed by record path.
fn manifest_identities(root: impl AsRef<Path>) -> BTreeMap<String, Object> {
    let manifest = load_json(root.as_ref(), "manifest.json").expect("manifest.json parses");
    let manifest = as_object(&manifest, "manifest.json").expect("manifest is an object");
    let Some(Value::Array(files)) = manifest.get("files") else {
        panic!("manifest: files must be an array");
    };
    files
        .iter()
        .map(|entry| {
            let entry = as_object(entry, "manifest files[]").expect("manifest entry is an object");
            let path = text_of(
                entry.get("path").expect("manifest entry carries a path"),
                "manifest path",
            )
            .expect("manifest path is text")
            .to_owned();
            let identity = match entry.get("identity") {
                Some(identity) => as_object(identity, "manifest identity")
                    .expect("manifest identity is an object")
                    .clone(),
                None => panic!("manifest entry for {path} carries no identity"),
            };
            (path, identity)
        })
        .collect()
}

/// Every member name the schema defines — top level plus each `$defs`
/// object's properties and requireds — the set the committed records must
/// collectively exercise.
fn schema_member_names(schema: &Object) -> Vec<String> {
    let mut names: Vec<String> = Vec::new();
    let mut collect = |container: &Object| {
        if let Some(Value::Object(properties)) = container.get("properties") {
            names.extend(properties.iter().map(|(name, _)| name.to_owned()));
        }
        if let Some(required) = container.get("required") {
            names.extend(text_list(required, "schema required").unwrap_or_default());
        }
    };
    collect(schema);
    if let Some(Value::Object(defs)) = schema.get("$defs") {
        for (_, definition) in defs.iter() {
            if let Ok(definition) = as_object(definition, "$defs entry") {
                collect(definition);
            }
        }
    }
    names.sort();
    names.dedup();
    names
}

/// The reserved member names the schema rejects by name.
fn reserved_fields(schema: &Object) -> Vec<String> {
    schema
        .get("x-archivist")
        .and_then(|meta| as_object(meta, "x-archivist").ok())
        .and_then(|meta| meta.get("reservedFields"))
        .map(|reserved| text_list(reserved, "reservedFields").unwrap_or_default())
        .unwrap_or_default()
}

/// The domain label of the family's digest construction, read from the
/// schema's `x-archivist.derivations` — never hardcoded here.
fn digest_label(schema: &Object) -> Result<String, String> {
    let archivist = schema
        .get("x-archivist")
        .ok_or("schema: x-archivist metadata is missing")?;
    let derivations = as_object(archivist, "x-archivist")?
        .get("derivations")
        .ok_or("schema: x-archivist.derivations is missing")?;
    let Value::Array(derivations) = derivations else {
        return Err("schema: derivations must be an array".to_string());
    };
    let first = derivations
        .first()
        .ok_or("schema: derivations must not be empty")?;
    let derivation = as_object(first, "derivations[0]")?;
    text_of(
        derivation
            .get("label")
            .ok_or("derivations[0]: label missing")?,
        "derivations[0].label",
    )
    .map(str::to_owned)
}

/// The `model-id` grammar, equivalent to the schema's pattern: a bounded
/// ASCII token that cannot carry prose — no whitespace, no control
/// characters, at most 128 bytes.
fn model_id_valid(text: &str) -> bool {
    let mut chars = text.chars();
    if !matches!(chars.next(), Some(first) if first.is_ascii_alphanumeric()) {
        return false;
    }
    text.len() <= 128
        && chars
            .all(|c| c.is_ascii_alphanumeric() || matches!(c, '.' | '_' | ':' | '/' | '+' | '-'))
}

/// The shared `sha256-hex` shape: exactly 64 lowercase hex characters.
fn sha256_hex_valid(text: &str) -> bool {
    text.len() == 64
        && text
            .bytes()
            .all(|b| b.is_ascii_digit() || (b'a'..=b'f').contains(&b))
}

/// A non-negative integer count in the shared `u63` shape (the protocol's
/// integer domain is i64; the u63 cap excludes the sign bit).
fn count_valid(value: &Value) -> bool {
    matches!(value, Value::Int(count) if *count >= 0)
}

/// Every object key anywhere in the record, plus one failure per null.
fn walk_values(failures: &mut Vec<String>, rel: &str, value: &Value, out: &mut Vec<String>) {
    match value {
        Value::Null => failures.push(format!("{rel}: null where a member is omitted")),
        Value::Array(items) => {
            for item in items {
                walk_values(failures, rel, item, out);
            }
        }
        Value::Object(object) => {
            for (name, member) in object.iter() {
                out.push(name.to_owned());
                walk_values(failures, rel, member, out);
            }
        }
        _ => {}
    }
}

/// Required members present, the closed shape, and the reserved `not`
/// block: every member schema-defined, no reserved name anywhere at the
/// top level.
fn check_shape(
    failures: &mut Vec<String>,
    rel: &str,
    record: &Object,
    required: &[String],
    properties: &Object,
    reserved: &[String],
) {
    for name in required {
        if !record.contains(name) {
            failures.push(format!("{rel}: required member {name} is missing"));
        }
    }
    for (name, _) in record.iter() {
        demand(
            failures,
            format!("{rel}: member {name} is not schema-defined"),
            properties.contains(name),
        );
        demand(
            failures,
            format!("{rel}: reserved member {name} is present"),
            !reserved.iter().any(|reserved| reserved == name),
        );
    }
}

/// Scalar identity members against the wire grammars this crate owns.
fn check_identity(failures: &mut Vec<String>, rel: &str, record: &Object) {
    demand(
        failures,
        format!(
            "{rel}: usage_summary_version must be 1, got {:?}",
            record.get("usage_summary_version")
        ),
        matches!(record.get("usage_summary_version"), Some(Value::Int(1))),
    );
    for (name, grammar) in [
        ("tenant_id", "tenant"),
        ("adapter_id", "adapter"),
        ("pipeline_version", "version"),
        ("adapter_projection_version", "version"),
    ] {
        let Some(value) = record.get(name) else {
            continue; // `required` already reported the absence
        };
        let Ok(text) = text_of(value, &format!("{rel}.{name}")) else {
            failures.push(format!("{rel}: {name} must be text"));
            continue;
        };
        let ok = match grammar {
            "tenant" => TenantId::parse(text).is_ok(),
            "adapter" => AdapterId::parse(text).is_ok(),
            _ => VersionToken::parse(text).is_ok(),
        };
        demand(
            failures,
            format!("{rel}: {name} = {text:?} fails its wire grammar"),
            ok,
        );
    }
    for name in ["occurrence_id", "usage_summary_digest"] {
        let Some(value) = record.get(name) else {
            continue;
        };
        match text_of(value, &format!("{rel}.{name}")) {
            Ok(text) => demand(
                failures,
                format!("{rel}: {name} is not a sha256 hex digest"),
                sha256_hex_valid(text),
            ),
            Err(e) => failures.push(e),
        }
    }
    match record.get("pipeline_id") {
        Some(Value::Text(pipeline)) => demand(
            failures,
            format!("{rel}: pipeline_id {pipeline:?} is outside the closed v1 enum"),
            pipeline == "usage",
        ),
        other => failures.push(format!("{rel}: pipeline_id must be text, got {other:?}")),
    }
    for name in ["model_id", "service_tier"] {
        if let Some(value) = record.get(name) {
            match text_of(value, &format!("{rel}.{name}")) {
                Ok(text) => demand(
                    failures,
                    format!("{rel}: {name} = {text:?} fails the bounded model-id grammar"),
                    model_id_valid(text),
                ),
                Err(e) => failures.push(e),
            }
        }
    }
}

/// The object key re-derives from the stored bytes alone and agrees with
/// the manifest's pinned identity.
fn check_object_key(
    failures: &mut Vec<String>,
    rel: &str,
    record: &Object,
    identity: &Object,
    key_pattern: &str,
) {
    let (Some(Value::Text(digest)), Some(Value::Text(tenant)), Some(Value::Text(version))) = (
        record.get("usage_summary_digest"),
        record.get("tenant_id"),
        record.get("pipeline_version"),
    ) else {
        return; // reported by the shape and identity checks
    };
    let key = format!(
        "tenants/{tenant}/v1/derived/usage/{version}/usage-summaries/{}/{}.json",
        &digest[..2],
        digest
    );
    demand(
        failures,
        format!("{rel}: re-derived key violates the pinned derived layout"),
        key.starts_with(&format!(
            "tenants/{tenant}/v1/derived/usage/1/usage-summaries/"
        )) && Path::new(&key)
            .extension()
            .is_some_and(|ext| ext.eq_ignore_ascii_case("json")),
    );
    demand(
        failures,
        format!("{rel}: object-key shard must be the digest's first two hex"),
        key_pattern.contains("[0-9a-f]{2}") && key.contains(&format!("/{}/", &digest[..2])),
    );
    match identity.get("object_key") {
        Some(Value::Text(manifest_key)) => demand(
            failures,
            format!("{rel}: manifest object key disagrees with the re-derived key"),
            manifest_key == &key,
        ),
        other => failures.push(format!(
            "{rel}: manifest identity has no object key: {other:?}"
        )),
    }
}

/// The `measured` branch: every count required, at least one summed
/// message, both ephemeral classes and no others.
fn check_measured(failures: &mut Vec<String>, rel: &str, usage: &Object) {
    for name in [
        "input_tokens",
        "output_tokens",
        "cache_read_tokens",
        "reasoning_tokens",
    ] {
        match usage.get(name) {
            Some(value) if count_valid(value) => {}
            Some(Value::Int(count)) => {
                failures.push(format!("{rel}: {name} must be non-negative, got {count}"));
            }
            other => failures.push(format!("{rel}: {name} must be an integer, got {other:?}")),
        }
    }
    match usage.get("assistant_message_count") {
        Some(Value::Int(count)) if *count >= 1 => {}
        Some(Value::Int(count)) => failures.push(format!(
            "{rel}: measured usage must sum at least one assistant message, got {count}"
        )),
        other => failures.push(format!(
            "{rel}: assistant_message_count must be an integer, got {other:?}"
        )),
    }
    match usage.get("cache_creation") {
        Some(Value::Object(cache)) => {
            for class in ["ephemeral_5m", "ephemeral_1h"] {
                match cache.get(class) {
                    Some(value) if count_valid(value) => {}
                    Some(Value::Int(count)) => failures.push(format!(
                        "{rel}: cache_creation.{class} must be non-negative, got {count}"
                    )),
                    other => failures.push(format!(
                        "{rel}: cache_creation.{class} must be an integer, got {other:?}"
                    )),
                }
            }
            demand(
                failures,
                format!("{rel}: cache_creation must carry exactly the two closed classes"),
                cache.len() == 2,
            );
        }
        other => failures.push(format!(
            "{rel}: cache_creation must be an object, got {other:?}"
        )),
    }
}

/// The `unknown` branch: a closed reason and nothing else — no count may
/// sit beside an `unknown`.
fn check_unknown(failures: &mut Vec<String>, rel: &str, usage: &Object) {
    demand(
        failures,
        format!("{rel}: an unknown usage carries no count member at all"),
        usage.len() == 2,
    );
    match usage.get("reason") {
        Some(Value::Text(reason)) => demand(
            failures,
            format!("{rel}: unknown reason {reason:?} is outside the closed v1 set"),
            matches!(reason.as_str(), "absent" | "malformed" | "unsupported"),
        ),
        other => failures.push(format!("{rel}: unknown reason must be text, got {other:?}")),
    }
}

#[test]
fn corpus_manifest_pins_the_committed_bytes() {
    let root = corpus_root();
    let mut failures = Vec::new();

    let entries = manifest_entries(&root).expect("manifest.json parses");
    demand(
        &mut failures,
        format!(
            "manifest: expected the five scenario records, got {}",
            entries.len()
        ),
        entries.len() == 5,
    );
    for (rel, bytes, sha) in &entries {
        match read(&root, rel) {
            Ok(actual) => {
                demand(
                    &mut failures,
                    format!("{rel}: byte count drifted from the manifest"),
                    actual.len() == *bytes,
                );
                demand(
                    &mut failures,
                    format!("{rel}: sha256 drifted from the manifest"),
                    sha256::encode_hex(&sha256::digest(&actual)) == *sha,
                );
            }
            Err(e) => failures.push(e),
        }
    }

    // No stray files beside the manifest and the pinned records.
    let mut on_disk: Vec<String> = fs::read_dir(&root)
        .expect("the corpus directory is committed")
        .filter_map(std::result::Result::ok)
        .flat_map(|top| {
            let top = top.path();
            if top.is_dir() {
                fs::read_dir(&top)
                    .expect("corpus subdirectory reads")
                    .filter_map(std::result::Result::ok)
                    .map(|entry| {
                        top.file_name().unwrap().to_string_lossy().into_owned()
                            + "/"
                            + &entry.file_name().to_string_lossy()
                    })
                    .collect::<Vec<_>>()
            } else {
                vec![top.file_name().unwrap().to_string_lossy().into_owned()]
            }
        })
        .collect();
    on_disk.sort();
    let mut expected: Vec<String> = entries.iter().map(|(rel, _, _)| rel.clone()).collect();
    expected.push("manifest.json".to_string());
    expected.sort();
    demand(
        &mut failures,
        format!("corpus directory contents drifted from the manifest: {on_disk:?}"),
        on_disk == expected,
    );

    assert!(failures.is_empty(), "{}", failures.join("\n"));
}

#[test]
fn records_are_canonical_closed_and_schema_shaped() {
    let root = corpus_root();
    let schema = load_json(
        schema_path().parent().unwrap(),
        schema_path().file_name().unwrap().to_str().unwrap(),
    )
    .expect("usage-summary.json parses");
    let schema = as_object(&schema, "usage-summary.json").expect("schema is an object");
    let common = load_json(
        common_schema_path().parent().unwrap(),
        common_schema_path().file_name().unwrap().to_str().unwrap(),
    )
    .expect("common.json parses");
    let common = as_object(&common, "common.json").expect("common.json is an object");

    let required = text_list(
        schema
            .get("required")
            .expect("schema pins required members"),
        "schema required",
    )
    .expect("schema required is a string array");
    let properties = match schema.get("properties") {
        Some(Value::Object(properties)) => properties.clone(),
        _ => panic!("schema: properties must be an object"),
    };
    let reserved = reserved_fields(schema);
    assert!(
        !reserved.is_empty(),
        "schema: reserved list must not be empty"
    );
    let key_pattern = common
        .get("$defs")
        .and_then(|defs| as_object(defs, "common.json $defs").ok())
        .and_then(|defs| defs.get("usage-summary-object-key"))
        .and_then(|shape| as_object(shape, "usage-summary-object-key").ok())
        .and_then(|shape| shape.get("pattern"))
        .and_then(|pattern| text_of(pattern, "usage-summary-object-key.pattern").ok())
        .map(str::to_owned)
        .expect("common.json owns the usage-summary-object-key pattern");

    let identities = manifest_identities(&root);
    let entries = manifest_entries(&root).expect("manifest.json parses");
    let mut failures = Vec::new();
    let mut exercised: Vec<String> = Vec::new();

    for (rel, _, _) in entries {
        let Ok(raw) = read(&root, &rel) else {
            continue; // the manifest test reports the missing file
        };
        let parsed = match json::parse(&raw) {
            Ok(value) => value,
            Err(e) => {
                failures.push(format!("{rel}: {e}"));
                continue;
            }
        };

        // Canonical serialization: the file is exactly the canonical bytes
        // plus one trailing LF.
        let mut canonical = parsed.canonical_bytes();
        canonical.push(b'\n');
        demand(
            &mut failures,
            format!("{rel}: file is not its canonical rendering plus one LF"),
            canonical == raw,
        );

        let Ok(record) = as_object(&parsed, &rel) else {
            failures.push(format!("{rel}: record must be an object"));
            continue;
        };
        check_shape(
            &mut failures,
            &rel,
            record,
            &required,
            &properties,
            &reserved,
        );
        check_identity(&mut failures, &rel, record);
        walk_values(&mut failures, &rel, &parsed, &mut exercised);
        check_object_key(&mut failures, &rel, record, &identities[&rel], &key_pattern);
    }

    // The committed records collectively exercise every member the schema
    // defines — required and optional, measured and unknown, both
    // ephemeral classes.
    exercised.sort();
    exercised.dedup();
    for name in schema_member_names(schema) {
        demand(
            &mut failures,
            format!("corpus: schema member {name} is never exercised by any record"),
            exercised.iter().any(|seen| seen == &name),
        );
    }

    assert!(failures.is_empty(), "{}", failures.join("\n"));
}

#[test]
fn harness_usage_follows_the_two_state_contract() {
    let root = corpus_root();
    let mut failures = Vec::new();

    let mut measured_records = 0usize;
    let mut unknown_records = 0usize;
    let mut digests: Vec<String> = Vec::new();

    for (rel, _, _) in manifest_entries(&root).expect("manifest.json parses") {
        let parsed = load_json(&root, &rel).expect("record parses");
        let record = as_object(&parsed, &rel).expect("record is an object");
        match record.get("usage_summary_digest") {
            Some(Value::Text(digest)) => digests.push(digest.clone()),
            other => {
                failures.push(format!(
                    "{rel}: usage_summary_digest must be text, got {other:?}"
                ));
            }
        }

        let Some(usage) = record.get("harness_usage") else {
            failures.push(format!(
                "{rel}: harness_usage is missing — the bounded state is mandatory"
            ));
            continue;
        };
        let Ok(usage) = as_object(usage, &format!("{rel}.harness_usage")) else {
            failures.push(format!("{rel}: harness_usage must be an object"));
            continue;
        };
        match usage.get("state") {
            Some(Value::Text(state)) if state == "measured" => {
                measured_records += 1;
                check_measured(&mut failures, &rel, usage);
            }
            Some(Value::Text(state)) if state == "unknown" => {
                unknown_records += 1;
                check_unknown(&mut failures, &rel, usage);
            }
            other => failures.push(format!(
                "{rel}: harness_usage.state must be measured or unknown, got {other:?}"
            )),
        }
    }

    // The corpus pins both states and pairwise-distinct identities.
    demand(
        &mut failures,
        format!(
            "corpus: expected measured and unknown fixtures, got {measured_records} measured / {unknown_records} unknown"
        ),
        measured_records >= 1 && unknown_records >= 1,
    );
    let mut distinct = digests.clone();
    distinct.sort();
    distinct.dedup();
    demand(
        &mut failures,
        "corpus: usage summary digests must be pairwise distinct".to_string(),
        distinct.len() == digests.len(),
    );

    assert!(failures.is_empty(), "{}", failures.join("\n"));
}

#[test]
fn digests_recompute_with_the_pinned_construction() {
    let schema = load_json(
        schema_path().parent().unwrap(),
        schema_path().file_name().unwrap().to_str().unwrap(),
    )
    .expect("usage-summary.json parses");
    let label =
        digest_label(as_object(&schema, "usage-summary.json").expect("schema is an object"))
            .expect("schema pins a digest construction");
    assert_eq!(
        label, "usage-summary-v1",
        "the schema must pin the usage-summary-v1 construction"
    );

    let root = corpus_root();
    for (rel, _, _) in manifest_entries(&root).expect("manifest.json parses") {
        let parsed = load_json(&root, &rel).expect("record parses");
        let mut record = as_object(&parsed, &rel)
            .expect("record is an object")
            .clone();
        let Some(Value::Text(committed)) = record.remove("usage_summary_digest") else {
            panic!("{rel}: usage_summary_digest must be text");
        };
        // Construction `usage-summary-v1` (VAL-005 self-verification): the
        // labeled frame over the record's own canonical bytes with the
        // digest member removed.
        let mut builder = FrameBuilder::new(&label);
        builder.push_bytes(&Value::Object(record).canonical_bytes());
        let frame = builder.finish();
        assert_eq!(
            sha256::encode_hex(&frame),
            committed,
            "{rel}: usage_summary_digest is not the {label} digest of the record's own canonical bytes"
        );
    }
}

#[test]
fn citations_name_provenance_bundle_occurrences() {
    let mut failures = Vec::new();

    let mut manifests: Vec<String> = fs::read_dir(provenance_root())
        .expect("the raw-provenance bundle must be committed beside this corpus")
        .filter_map(std::result::Result::ok)
        .map(|entry| entry.file_name().to_string_lossy().into_owned())
        .filter(|name| {
            Path::new(name)
                .extension()
                .is_some_and(|ext| ext.eq_ignore_ascii_case("json"))
        })
        .collect();
    manifests.sort();
    assert!(
        !manifests.is_empty(),
        "the provenance bundle lists no occurrences"
    );

    let mut provenance: Vec<String> = Vec::new();
    for rel in &manifests {
        match load_json(provenance_root(), rel) {
            Ok(value) => {
                let manifest =
                    as_object(&value, "occurrence manifest").expect("manifest is an object");
                match manifest.get("occurrence_id") {
                    Some(Value::Text(id)) => provenance.push(id.clone()),
                    other => {
                        failures.push(format!("{rel}: occurrence_id must be text, got {other:?}"));
                    }
                }
            }
            Err(e) => failures.push(e),
        }
    }

    let root = corpus_root();
    for (rel, _, _) in manifest_entries(&root).expect("manifest.json parses") {
        let parsed = load_json(&root, &rel).expect("record parses");
        let record = as_object(&parsed, &rel).expect("record is an object");
        match record.get("occurrence_id") {
            Some(Value::Text(occurrence)) => demand(
                &mut failures,
                format!(
                    "{rel}: cites occurrence {occurrence}, which the provenance bundle does not materialize"
                ),
                provenance.iter().any(|known| known == occurrence),
            ),
            other => failures.push(format!("{rel}: occurrence_id must be text, got {other:?}")),
        }
    }

    assert!(failures.is_empty(), "{}", failures.join("\n"));
}
