[package]
name = "archivist-storage-s3"
description = "Portable S3 implementation of the Archivist storage traits"
publish = false
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
archivist-protocol = { path = "../archivist-protocol" }
archivist-storage = { path = "../archivist-storage" }

[lints]
workspace = true
