#!/usr/bin/env python3
"""Deterministic synthetic fixture generator for Agent Archivist.

Implements the Phase 0 deliverable "a deterministic synthetic fixture
generator; do not hand-copy real sessions" (docs/plan/plan.md, Section 8) and
produces the corpus categories the adapter-test contract names: normal,
large, malformed, partially written, and rewritten synthetic sessions
(plan Section 10, "Adapter tests"). Nothing in the corpus is copied from any
real harness store: every byte is derived from a closed vocabulary, fixed
identifier shapes, and a seeded deterministic bit generator.

Corpus layout under ``fixtures/synthetic`` (plan Section 6)::

    sessions/    normal complete sessions, plus additive-fields.jsonl
                 (forward-compat optional fields) and truncated-life.jsonl
                 (valid records, session never ended)
    rewritten/   per session, generation snapshots gen-000N.jsonl whose
                 earlier lines are byte-identical to the previous generation,
                 followed by a compaction record and fresh records
    large/       marathon/ (one month-scale session) and history/
                 (several synthetic accounts, many sessions each)
    malformed/   one file per defect, tagged in the manifest
    manifest.json  schema, seed, shape parameters, per-file digests

Determinism model:

1. The only entropy source is a SHA-256 counter-mode DRBG keyed by the
   recorded seed string. No clock, environment, locale, hostname, or
   ``random`` module is involved; newline is always ``\\n`` and timestamps
   are rendered from integer arithmetic, so regeneration is byte-identical
   across platforms and Python versions.
2. The committed ``manifest.json`` records the schema string, the seed, the
   corpus shape parameters, and one SHA-256 digest per file. ``--verify``
   regenerates the corpus from the manifest seed with the current code and
   byte-compares every file against the working tree, so any drift between
   code, corpus, and manifest fails the gate.
3. Changing the vocabulary, record shapes, or corpus counts changes the
   regenerated bytes; the workflow is then to rerun ``--generate``, and
   commit the corpus, manifest, and code together.

Content safety — the acceptance property is that scans find no private
transcript, credential, path, hostname, or account identifier. That is
enforced constructively and then verified:

1. Constructively: record text is drawn from a fixed word list, identifiers
   are UUIDv4-shaped, ``acct-``+hex, ``proj-word-word``, or
   ``synthetic-word-NNN`` labels, timestamps are integers over a fixed
   window, and the serializer emits no ``/`` or ``@`` byte anywhere, so no
   path, URL, email, or handle can appear.
2. By scan (``--verify``): every ASCII letter run must be a closed-vocabulary
   or structural token (pure ``a-f`` runs are permitted as artifacts of
   synthetic hex identifiers); parseable lines must contain only allowlisted
   keys and string values matching the synthetic shapes; raw ``/`` and ``@``
   bytes, an infrastructure denylist, and credential-shape markers must be
   absent.

Output safety: findings name the rule, file, and line only, never the
matched bytes — the same redaction ethos as the secret-scan lanes. On any
failure the tool prints a report to stderr and exits 2; on success it prints
a content-free summary (counts, bytes, digests) and exits 0.

Usage::

    tools/fixturegen.py --verify              # gate: regenerate, byte-compare, scan
    tools/fixturegen.py --generate OUTPUT     # write corpus + manifest to OUTPUT
    tools/fixturegen.py --generate OUTPUT --seed SEED   # non-canonical seed

``--generate`` refuses to overwrite an output directory that is not the
canonical corpus location unless ``--force`` is given, guarding against
accidentally clobbering an unrelated tree. Standard-library only, so a clean
checkout can run it before any dependency is fetched.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CANONICAL_OUTPUT = ROOT / "fixtures" / "synthetic"
MANIFEST_NAME = "manifest.json"

# Corpus identity. Bumping the schema string is a corpus-format version
# event: regenerate and commit corpus + manifest + code together.
SCHEMA = "archivist.synthetic-fixtures/v1"
SCAN_VERSION = 1
CANONICAL_SEED = "archivist-phase0-synthetic-2026-09-11"

# Corpus shape. Recorded verbatim in the manifest and pinned by --verify so
# a shape edit without regeneration fails loudly instead of silently.
PARAMS: dict[str, object] = {
    "normal_sessions": 8,
    "additive_fields_file": "sessions/additive-fields.jsonl",
    "truncated_life_file": "sessions/truncated-life.jsonl",
    "rewritten_sessions": 2,
    "rewritten_generations": 3,
    "marathon_records": 1200,
    "history_accounts": 6,
    "history_sessions_per_account": 12,
    "malformed_defects": [
        "empty",
        "blank-lines",
        "invalid-json-line",
        "non-object-line",
        "missing-type",
        "wrong-type-id",
        "duplicate-ids",
        "nul-byte",
        "invalid-utf8",
        "truncated-tail",
    ],
}

# Recording vocabulary: common nature words, deliberately free of any
# technology, credential, infrastructure, or person-adjacent term. This is
# the closed set from which all record text is assembled.
NOUNS = (
    "heron", "estuary", "beacon", "meadow", "canyon", "driftwood", "lichen",
    "tributary", "marsh", "falcon", "pebble", "glacier", "orchard", "thicket",
    "lantern", "harbor", "prairie", "cedar", "rivulet", "boulder", "dune",
    "kite", "ember", "quarry", "willow", "cove", "wheat", "canal", "fjord",
    "atoll", "moraine", "savanna", "reed", "warbler", "clover", "summit",
)
ADJECTIVES = (
    "amber", "quiet", "slender", "violet", "hazy", "nimble", "solemn",
    "gentle", "rapid", "hollow", "lucid", "fertile", "arid", "coastal",
    "northern", "southern", "twin", "pale", "vast", "crisp", "mellow",
    "rustic", "tranquil", "uneven", "sturdy", "soft",
)
VERB_PAIRS = (
    ("drift", "drifts"), ("gather", "gathers"), ("mirror", "mirrors"),
    ("settle", "settles"), ("follow", "follows"), ("wander", "wanders"),
    ("listen", "listens"), ("return", "returns"), ("reach", "reaches"),
    ("cross", "crosses"), ("bend", "bends"), ("circle", "circles"),
)
VERB_BASES = tuple(base for base, _ in VERB_PAIRS)
VERB_THIRDS = tuple(third for _, third in VERB_PAIRS)
FUNCTION_WORDS = frozenset(
    {"the", "a", "and", "of", "past", "beside", "under", "near", "over",
     "toward", "with"}
)
# Both inflections are closed-vocabulary: sentences use the third-person
# forms, tool names the bases, and the scan allowlists both.
WORDS = (
    frozenset(NOUNS) | frozenset(ADJECTIVES)
    | frozenset(VERB_BASES) | frozenset(VERB_THIRDS)
)

TYPE_VALUES = (
    "session_start", "user", "assistant", "tool_use", "tool_result",
    "system", "compaction", "session_end",
)
REASON_VALUES = ("end", "limit", "interrupt")
ENUM_VALUES = frozenset(TYPE_VALUES) | frozenset(REASON_VALUES)

# Every JSON key the corpus may contain, including the additive-optional
# fields of the forward-compatibility session.
RECORD_KEYS = frozenset(
    {"type", "id", "ts", "text", "account", "project", "model", "schema",
     "records", "reason", "tokens", "tool", "args_bytes", "ok", "tool_ref",
     "bytes", "prior_records", "future_field", "vendor_note"}
)

UUID_RE = re.compile(
    r"^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
)
TS_RE = re.compile(r"^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z$")
ACCT_RE = re.compile(r"^acct-[0-9a-f]{8}$")
PROJ_RE = re.compile(r"^proj-[a-z]+(-[a-z]+){1,2}$")
MODEL_RE = re.compile(r"^synthetic-[a-z]+-\d{3}$")
TOOL_RE = re.compile(r"^[a-z]+_[a-z]+$")
HEX_WORD_RE = re.compile(r"^[a-f]{2,}$")
TOKEN_RE = re.compile(rb"[A-Za-z_]{2,}")

# Infrastructure and account markers that must never appear in the corpus.
# The closed vocabulary already excludes them; this list makes the scan name
# the concrete leakage classes (private hostnames, accounts, deployments).
DENYLIST = (
    b"ardenone", b"codinghome", b"hetzner", b"rackspace", b"jedarden",
    b"tailnet", b"ts.net",
)
CREDENTIAL_RES = (
    re.compile(rb"-----BEGIN [A-Z ]*PRIVATE KEY"),
    re.compile(rb"(?i)bearer [a-z0-9._-]{8,}"),
    re.compile(rb"sk-[A-Za-z0-9]{16,}"),
    re.compile(rb"ghp_[A-Za-z0-9]{20,}"),
    re.compile(rb"github_pat_[A-Za-z0-9_]{20,}"),
    re.compile(rb"AKIA[0-9A-Z]{16}"),
    re.compile(rb"xox[baprs]-[A-Za-z0-9-]{10,}"),
    re.compile(rb"(?i)\b(api[_-]?key|apikey|password|passwd|secret|credential)\b"),
    re.compile(rb"(?i)\btoken\b"),
)

ALLOWED_TOKENS = WORDS | FUNCTION_WORDS | RECORD_KEYS | ENUM_VALUES | {
    "proj", "acct", "synthetic", "true", "false",
}


class Drbg:
    """SHA-256 counter-mode deterministic bit generator.

    Keyed by the seed label and the seed string; each 32-byte block is
    ``H(key || counter_be64)``. Deterministic across platforms and Python
    versions because it depends only on integer arithmetic and SHA-256.
    """

    KEY_LABEL = b"agent-archivist fixturegen drbg v1"

    def __init__(self, seed: str) -> None:
        self._key = hashlib.sha256(
            self.KEY_LABEL + b"\0" + seed.encode("utf-8")
        ).digest()
        self._counter = 0
        self._buf = b""

    def take(self, n: int) -> bytes:
        """Return the next ``n`` bytes of the stream."""
        while len(self._buf) < n:
            block = hashlib.sha256(
                self._key + self._counter.to_bytes(8, "big")
            ).digest()
            self._buf += block
            self._counter += 1
        out, self._buf = self._buf[:n], self._buf[n:]
        return out

    def below(self, bound: int) -> int:
        """Uniform integer in ``[0, bound)`` via rejection sampling.

        Rejection keeps the mapping unbiased and deterministic; the bit
        width is fixed by ``bound`` so byte consumption is stable.
        """
        if bound <= 1:
            return 0
        bits = (bound - 1).bit_length()
        nbytes = (bits + 7) // 8
        mask = (1 << bits) - 1
        while True:
            value = int.from_bytes(self.take(nbytes), "big") & mask
            if value < bound:
                return value

    def hex(self, nbytes: int) -> str:
        """Return ``nbytes*2`` lowercase hex characters."""
        return self.take(nbytes).hex()

    def choice(self, seq):
        """Pick one element of ``seq``."""
        return seq[self.below(len(seq))]


def civil_from_days(days: int) -> tuple[int, int, int]:
    """Convert days since 1970-01-01 to a ``(year, month, day)`` triple.

    Howard Hinnant's ``civil_from_days``: pure integer arithmetic, valid for
    the whole render window and beyond.
    """
    z = days + 719468
    era = (z if z >= 0 else z - 146096) // 146097
    doe = z - era * 146097
    yoe = (doe - doe // 1460 + doe // 36524 - doe // 146096) // 365
    year = yoe + era * 400
    doy = doe - (365 * yoe + yoe // 4 - yoe // 100)
    mp = (5 * doy + 2) // 153
    day = doy - (153 * mp + 2) // 5 + 1
    month = mp + 3 if mp < 10 else mp - 9
    return (year + (1 if month <= 2 else 0), month, day)


# Fixed render window for synthetic timestamps: Monday 2026-01-05 through
# roughly the following four months. The conversion above is pure integer
# arithmetic (Hinnant's algorithm), so no datetime locale is consulted; the
# guard pins the epoch constant so a mis-typed day count cannot silently
# shift every rendered date.
BASE_DAY = 20458  # days from 1970-01-01 to 2026-01-05
if civil_from_days(BASE_DAY) != (2026, 1, 5):
    raise RuntimeError("BASE_DAY does not encode 2026-01-05")
BASE_TS = BASE_DAY * 86400
WINDOW_SECONDS = 120 * 86400


def format_ts(epoch_seconds: int) -> str:
    """Render whole seconds since the Unix epoch as ``YYYY-MM-DDTHH:MM:SSZ``."""
    days, rem = divmod(epoch_seconds, 86400)
    hour, rem = divmod(rem, 3600)
    minute, second = divmod(rem, 60)
    year, month, day = civil_from_days(days)
    return (
        f"{year:04d}-{month:02d}-{day:02d}"
        f"T{hour:02d}:{minute:02d}:{second:02d}Z"
    )


def jstr(value: str) -> bytes:
    """Serialize one JSON string literal as raw UTF-8 bytes.

    Escapes only what JSON requires (quote, backslash, control characters),
    so non-ASCII text is written as genuine multibyte UTF-8 rather than
    ``\\u`` escapes — the corpus is meant to exercise real UTF-8 handling.
    """
    out = bytearray(b'"')
    for ch in value:
        if ch == '"':
            out += b'\\"'
        elif ch == "\\":
            out += b"\\\\"
        elif ch < " ":
            out += b"\\u%04x" % ord(ch)
        else:
            out += ch.encode("utf-8")
    out += b'"'
    return bytes(out)


def jline(*pairs: tuple[str, object]) -> bytes:
    """Serialize one ordered JSON object as a single ``\\n``-terminated line.

    Field order is call order, values are ``str``/``int``/``bool`` only —
    integers everywhere, no floats, matching the workspace discipline.
    """
    parts = []
    for key, value in pairs:
        if isinstance(value, bool):
            encoded = b"true" if value else b"false"
        elif isinstance(value, int):
            encoded = str(value).encode("ascii")
        elif isinstance(value, str):
            encoded = jstr(value)
        else:
            raise TypeError(f"unsupported record value: {type(value)!r}")
        parts.append(jstr(key) + b": " + encoded)
    return b"{" + b", ".join(parts) + b"}\n"


def synth_uuid(d: Drbg) -> str:
    """UUIDv4-shaped identifier with version and variant bits set."""
    raw = bytearray(d.take(16))
    raw[6] = (raw[6] & 0x0F) | 0x40
    raw[8] = (raw[8] & 0x3F) | 0x80
    h = raw.hex()
    return f"{h[0:8]}-{h[8:12]}-{h[12:16]}-{h[16:20]}-{h[20:32]}"


def synth_account(d: Drbg) -> str:
    """Synthetic account label: ``acct-`` plus eight hex digits."""
    return "acct-" + d.hex(4)


def synth_project(d: Drbg) -> str:
    """Synthetic project label: ``proj-adjective-noun``."""
    return f"proj-{d.choice(ADJECTIVES)}-{d.choice(NOUNS)}"


def synth_model(d: Drbg) -> str:
    """Synthetic model label: ``synthetic-noun-NNN``."""
    return f"synthetic-{d.choice(NOUNS)}-{100 + d.below(900):03d}"


def synth_tool(d: Drbg) -> str:
    """Synthetic tool name: two vocabulary words joined by an underscore."""
    return f"{d.choice(NOUNS)}_{d.choice(VERB_BASES)}"


def sentence(d: Drbg) -> str:
    """Assemble a short synthetic sentence from the closed vocabulary."""
    form = d.below(3)
    if form == 0:
        body = (
            f"the {d.choice(ADJECTIVES)} {d.choice(NOUNS)} "
            f"{d.choice(VERB_THIRDS)} past the {d.choice(ADJECTIVES)} "
            f"{d.choice(NOUNS)}"
        )
    elif form == 1:
        body = (
            f"the {d.choice(NOUNS)} {d.choice(VERB_THIRDS)} beside the "
            f"{d.choice(NOUNS)}, and the {d.choice(NOUNS)} "
            f"{d.choice(VERB_THIRDS)}"
        )
    else:
        body = (
            f"the {d.choice(ADJECTIVES)} {d.choice(NOUNS)} "
            f"{d.choice(VERB_THIRDS)} under a {d.choice(ADJECTIVES)} "
            f"{d.choice(NOUNS)} near the {d.choice(NOUNS)}"
        )
    return body[0].upper() + body[1:] + "."


def body_lines(
    d: Drbg,
    count: int,
    start_ts: int,
    max_gap: int,
    extra_fields: bool = False,
) -> list[bytes]:
    """Generate ``count`` session body records after ``session_start``.

    Timestamps advance monotonically by whole seconds; tool results always
    follow the tool use they reference. With ``extra_fields`` every
    assistant record also carries the additive-optional fields the
    forward-compatibility session exercises.
    """
    ts = start_ts
    lines: list[bytes] = []
    pending_tool: str | None = None
    for _ in range(count):
        ts += 1 + d.below(max_gap)
        kind = d.below(10)
        if kind < 4:
            pairs: list[tuple[str, object]] = [
                ("type", "user"), ("id", synth_uuid(d)),
                ("ts", format_ts(ts)), ("text", sentence(d)),
            ]
        elif kind < 7:
            pairs = [
                ("type", "assistant"), ("id", synth_uuid(d)),
                ("ts", format_ts(ts)), ("text", sentence(d)),
                ("tokens", 40 + d.below(4000)),
            ]
            if extra_fields:
                pairs.append(("future_field", d.below(1000)))
                pairs.append(("vendor_note", sentence(d)))
        elif kind < 9:
            pending_tool = synth_uuid(d)
            pairs = [
                ("type", "tool_use"), ("id", pending_tool),
                ("ts", format_ts(ts)), ("tool", synth_tool(d)),
                ("args_bytes", 16 + d.below(4096)),
                ("ok", d.below(8) != 0),
            ]
        elif pending_tool is not None:
            pairs = [
                ("type", "tool_result"), ("id", synth_uuid(d)),
                ("ts", format_ts(ts)), ("tool_ref", pending_tool),
                ("bytes", 16 + d.below(16384)),
            ]
            pending_tool = None
        else:
            pairs = [
                ("type", "system"), ("id", synth_uuid(d)),
                ("ts", format_ts(ts)), ("text", sentence(d)),
            ]
        lines.append(jline(*pairs))
    return lines


def synth_session(
    d: Drbg,
    *,
    account: str,
    start_ts: int,
    body_count: int,
    max_gap: int,
    extra_fields: bool = False,
    sid: str | None = None,
    project: str | None = None,
    model: str | None = None,
) -> list[bytes]:
    """Generate one complete synthetic session as ``\\n``-terminated lines."""
    sid = sid or synth_uuid(d)
    project = project or synth_project(d)
    model = model or synth_model(d)
    lines = [jline(
        ("type", "session_start"), ("id", sid), ("ts", format_ts(start_ts)),
        ("account", account), ("project", project), ("model", model),
        ("schema", 1),
    )]
    lines += body_lines(
        d, body_count, start_ts, max_gap, extra_fields=extra_fields
    )
    end_ts = start_ts + (body_count + 2) * (1 + max_gap)
    lines.append(jline(
        ("type", "session_end"), ("id", synth_uuid(d)), ("ts", format_ts(end_ts)),
        ("records", len(lines) + 1), ("reason", d.choice(REASON_VALUES)),
    ))
    return lines


def end_line(d: Drbg, ts: int, records: int) -> bytes:
    """Standalone ``session_end`` line for hand-assembled sessions."""
    return jline(
        ("type", "session_end"), ("id", synth_uuid(d)), ("ts", format_ts(ts)),
        ("records", records), ("reason", d.choice(REASON_VALUES)),
    )


def build_malformed(d: Drbg) -> tuple[dict[str, bytes], dict[str, dict]]:
    """Build the one-file-per-defect malformed corpus.

    Each file starts from generator output and then carries exactly one
    named byte- or record-level defect, so a future adapter test can target
    one failure mode per file. Defects that splice raw bytes (NUL, broken
    UTF-8) are placed between whole vocabulary words or inside multibyte
    characters so the content scan still proves no foreign text entered.
    """
    files: dict[str, bytes] = {}
    tags: dict[str, dict] = {}

    def add(name: str, data: bytes) -> None:
        path = f"malformed/{name}.jsonl"
        files[path] = data
        tags[path] = {"defect": name}

    add("empty", b"")

    tiny = synth_session(
        d, account=synth_account(d), start_ts=BASE_TS + d.below(WINDOW_SECONDS),
        body_count=2, max_gap=60,
    )
    add("blank-lines", tiny[0] + b"\n" + b"   " + tiny[1] + b"\n" + tiny[2])

    cut = tiny[0] + tiny[1] + b'{"type": "user", "id":\n' + tiny[2]
    add("invalid-json-line", cut)

    add("non-object-line", tiny[0] + b"[0, 1, 2]\n" + tiny[1] + tiny[2])

    add("missing-type", jline(
        ("id", synth_uuid(d)),
        ("ts", format_ts(BASE_TS + d.below(WINDOW_SECONDS))),
        ("text", sentence(d)),
    ) + tiny[1])

    add("wrong-type-id", jline(
        ("type", "user"), ("id", 12345),
        ("ts", format_ts(BASE_TS + d.below(WINDOW_SECONDS))),
        ("text", sentence(d)),
    ) + tiny[1])

    shared = synth_uuid(d)
    first = jline(
        ("type", "user"), ("id", shared),
        ("ts", format_ts(BASE_TS + d.below(WINDOW_SECONDS))),
        ("text", sentence(d)),
    )
    second = jline(
        ("type", "system"), ("id", shared),
        ("ts", format_ts(BASE_TS + d.below(WINDOW_SECONDS))),
        ("text", sentence(d)),
    )
    add("duplicate-ids", tiny[0] + first + second)

    # Raw NUL between two whole words inside a text value.
    nul_text = sentence(d)
    words = nul_text.split(" ")
    split_at = 1 + d.below(len(words) - 1)
    nul_line = (
        jstr("type") + b": " + jstr("user") + b", "
        + jstr("id") + b": " + jstr(synth_uuid(d)) + b", "
        + jstr("ts") + b": " + jstr(format_ts(BASE_TS + d.below(WINDOW_SECONDS))) + b", "
        + jstr("text") + b": "
        + jstr(" ".join(words[:split_at])).rstrip(b'"') + b"\x00"
        + jstr(" ".join(words[split_at:])).lstrip(b'"') + b"}\n"
    )
    add("nul-byte", tiny[0] + nul_line + tiny[1])

    # One continuation byte dropped from a multibyte character at the end of
    # a newline-terminated line: the line structure survives, decoding it
    # does not. The lead byte and remaining continuation stay non-ASCII, so
    # no ASCII token runs are created.
    cjk = "語"  # 3-byte UTF-8 character
    utf_line = jline(
        ("type", "user"), ("id", synth_uuid(d)),
        ("ts", format_ts(BASE_TS + d.below(WINDOW_SECONDS))),
        ("text", sentence(d)[:-1] + " " + cjk),
    )
    whole = cjk.encode("utf-8")
    broken = utf_line.replace(whole + b'"}', whole[:2] + b'"}', 1)
    if broken == utf_line:  # pragma: no cover - construction is by design
        raise AssertionError("invalid-utf8 splice point not found")
    add("invalid-utf8", tiny[0] + broken + tiny[1])

    # Torn tail: the final record loses exactly its closing quote and
    # newline, so the file ends inside a complete word — partially written
    # without splitting a vocabulary token.
    torn = tiny[0] + tiny[1] + tiny[2] + tiny[1]
    add("truncated-tail", torn[:-3])

    return files, tags


def build_corpus(seed: str) -> tuple[dict[str, bytes], dict[str, dict]]:
    """Build the full synthetic corpus: ``path -> content`` plus tags.

    The DRBG call order is fixed by this function, so one seed yields one
    byte-exact corpus.
    """
    d = Drbg(seed)
    files: dict[str, bytes] = {}
    tags: dict[str, dict] = {}

    for _ in range(int(PARAMS["normal_sessions"])):
        lines = synth_session(
            d, account=synth_account(d),
            start_ts=BASE_TS + d.below(WINDOW_SECONDS),
            body_count=5 + d.below(30), max_gap=900,
        )
        sid = lines[0].split(b'"')[7].decode("ascii")
        files[f"sessions/session-{sid}.jsonl"] = b"".join(lines)

    additive = synth_session(
        d, account=synth_account(d),
        start_ts=BASE_TS + d.below(WINDOW_SECONDS),
        body_count=6 + d.below(10), max_gap=900, extra_fields=True,
    )
    files[str(PARAMS["additive_fields_file"])] = b"".join(additive)
    tags[str(PARAMS["additive_fields_file"])] = {
        "note": "additive optional fields alongside the v1 record set"
    }

    sid = synth_uuid(d)
    start = BASE_TS + d.below(WINDOW_SECONDS)
    truncated = [jline(
        ("type", "session_start"), ("id", sid), ("ts", format_ts(start)),
        ("account", synth_account(d)), ("project", synth_project(d)),
        ("model", synth_model(d)), ("schema", 1),
    )]
    truncated += body_lines(d, 1, start, 60)
    files[str(PARAMS["truncated_life_file"])] = b"".join(truncated)
    tags[str(PARAMS["truncated_life_file"])] = {
        "note": "valid records only; the session never ended"
    }

    for _ in range(int(PARAMS["rewritten_sessions"])):
        sid = synth_uuid(d)
        account = synth_account(d)
        start = BASE_TS + d.below(WINDOW_SECONDS)
        previous = synth_session(
            d, account=account, start_ts=start, sid=sid,
            body_count=12 + d.below(12), max_gap=600,
        )
        files[f"rewritten/{sid}/gen-0001.jsonl"] = b"".join(previous)
        for gen in range(2, int(PARAMS["rewritten_generations"]) + 1):
            # Byte-identical prefix of the previous generation, then a
            # compaction record and fresh records: a rewrite, not an append.
            keep = 2 + d.below(len(previous) - 3)
            prefix = previous[:keep]
            gen_start = start + gen * 86400 * (1 + d.below(3))
            fresh = [jline(
                ("type", "compaction"), ("id", synth_uuid(d)),
                ("ts", format_ts(gen_start)), ("prior_records", keep),
            )]
            fresh += body_lines(d, 4 + d.below(8), gen_start, 600)
            fresh.append(end_line(d, gen_start + 7200, keep + len(fresh)))
            previous = prefix + fresh
            files[f"rewritten/{sid}/gen-{gen:04d}.jsonl"] = b"".join(previous)

    marathon = synth_session(
        d, account=synth_account(d),
        start_ts=BASE_TS + d.below(WINDOW_SECONDS),
        body_count=int(PARAMS["marathon_records"]) - 2, max_gap=7200,
    )
    msid = marathon[0].split(b'"')[7].decode("ascii")
    files[f"large/marathon/session-{msid}.jsonl"] = b"".join(marathon)
    tags[f"large/marathon/session-{msid}.jsonl"] = {
        "note": "month-scale single session for incremental-capture tests"
    }

    for _ in range(int(PARAMS["history_accounts"])):
        account = synth_account(d)
        for _ in range(int(PARAMS["history_sessions_per_account"])):
            lines = synth_session(
                d, account=account,
                start_ts=BASE_TS + d.below(WINDOW_SECONDS),
                body_count=6 + d.below(16), max_gap=1200,
            )
            sid = lines[0].split(b'"')[7].decode("ascii")
            files[f"large/history/{account}/session-{sid}.jsonl"] = b"".join(lines)

    malformed, malformed_tags = build_malformed(d)
    files.update(malformed)
    tags.update(malformed_tags)
    return files, tags


def sha256_hex(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def corpus_digest(files: dict[str, bytes]) -> str:
    """Digest over the sorted ``path sha256 size`` lines of the corpus."""
    lines = sorted(
        f"{path} {sha256_hex(data)} {len(data)}" for path, data in files.items()
    )
    return sha256_hex("\n".join(lines).encode("utf-8") + b"\n")


def build_manifest(seed: str, files: dict[str, bytes], tags: dict[str, dict]) -> bytes:
    """Serialize the corpus manifest: identity, seed, shape, per-file digests."""
    manifest = {
        "schema": SCHEMA,
        "scan_version": SCAN_VERSION,
        "seed": seed,
        "params": PARAMS,
        "corpus_digest": corpus_digest(files),
        "files": [
            {"path": path, "sha256": sha256_hex(data), "bytes": len(data)}
            | tags.get(path, {})
            for path, data in sorted(files.items())
        ],
    }
    return json.dumps(manifest, indent=2, sort_keys=True).encode("utf-8") + b"\n"


def line_of(data: bytes, offset: int) -> int:
    """1-based line number of ``offset`` within ``data``."""
    return data.count(b"\n", 0, offset) + 1


def is_synthetic_sentence(value: str) -> bool:
    """True when every word of ``value`` is closed-vocabulary."""
    core = value[:-1] if value.endswith(".") else value
    words = [w.strip(".,") for w in core.split(" ")]
    if not words or any(not w for w in words):
        return False
    return all(w.lower() in WORDS | FUNCTION_WORDS for w in words)


def string_is_synthetic(value: str) -> bool:
    """True when ``value`` matches one of the synthetic identifier shapes."""
    if value in ENUM_VALUES or UUID_RE.match(value) or TS_RE.match(value):
        return True
    if ACCT_RE.match(value) or MODEL_RE.match(value):
        return True
    if PROJ_RE.match(value) and all(
        w in WORDS for w in value[5:].split("-")
    ):
        return True
    if TOOL_RE.match(value) and all(
        w in WORDS for w in value.split("_")
    ):
        return True
    return is_synthetic_sentence(value)


def scan_corpus(files: dict[str, bytes]) -> list[str]:
    """Content-scan the corpus; return content-free findings.

    Four rules, in order: raw byte markers (``/``, ``@``, denylist,
    credential shapes), closed-vocabulary token check over all bytes,
    allowlisted-key check over parseable lines, and synthetic-shape check
    over string values of parseable lines. Findings name the rule, file,
    and line — never the matched bytes.
    """
    findings: list[str] = []

    def report(path: str, line: int, rule: str) -> None:
        findings.append(f"{rule} {path}:{line}")

    for path in sorted(files):
        data = files[path]
        lowered = data.lower()
        for rule, marker in (("forbidden-byte", b"/"), ("forbidden-byte", b"@")):
            offset = data.find(marker)
            if offset != -1:
                report(path, line_of(data, offset), rule)
        for marker in DENYLIST:
            offset = lowered.find(marker)
            if offset != -1:
                report(path, line_of(data, offset), "denylist")
        for pattern in CREDENTIAL_RES:
            match = pattern.search(data)
            if match:
                report(path, line_of(data, match.start()), "credential-marker")

        for match in TOKEN_RE.finditer(data):
            token = match.group().decode("ascii")
            # Sentences capitalize their first word, so the closed-vocabulary
            # check is case-insensitive; every allowlisted token is
            # lowercase, and structural leakage markers carry punctuation
            # or non-vocabulary letters this rule still rejects. A token
            # passes as a unit (record keys, enum values) or, for
            # underscore-joined tool names, part by part.
            if token.lower() in ALLOWED_TOKENS:
                continue
            parts = token.split("_")
            if all(
                part.lower() in ALLOWED_TOKENS
                or (part and bool(HEX_WORD_RE.fullmatch(part)))
                for part in parts
            ):
                continue
            report(path, line_of(data, match.start()), "unknown-token")

        offset = 0
        for raw in data.split(b"\n"):
            line_number = line_of(data, offset)
            if raw:
                try:
                    record = json.loads(raw)
                except (ValueError, UnicodeDecodeError):
                    record = None
                if isinstance(record, dict):
                    for key, value in record.items():
                        if key not in RECORD_KEYS:
                            report(path, line_number, "unknown-key")
                        if isinstance(value, str) and not string_is_synthetic(value):
                            report(path, line_number, "foreign-string")
            offset += len(raw) + 1

    return findings


def cmd_generate(args: argparse.Namespace) -> int:
    output = Path(args.generate).resolve()
    if output == CANONICAL_OUTPUT.resolve():
        pass  # regenerating the committed corpus is the normal workflow
    elif output.exists() and any(output.iterdir()) and not args.force:
        print(
            f"error: {output} exists and is not empty; pass --force to overwrite",
            file=sys.stderr,
        )
        return 2
    if output.exists():
        shutil.rmtree(output)
    output.mkdir(parents=True)

    files, tags = build_corpus(args.seed)
    for path in sorted(files):
        target = output / path
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(files[path])
    (output / MANIFEST_NAME).write_bytes(build_manifest(args.seed, files, tags))

    print(f"schema: {SCHEMA}")
    print(f"seed: {args.seed}")
    print(f"files: {len(files)}")
    print(f"bytes: {sum(len(v) for v in files.values())}")
    print(f"corpus_digest: {corpus_digest(files)}")
    print(f"output: {output}")
    return 0


def cmd_verify(args: argparse.Namespace) -> int:
    corpus_dir = Path(args.root).resolve() / "fixtures" / "synthetic"
    manifest_path = corpus_dir / MANIFEST_NAME
    problems: list[str] = []

    if not manifest_path.is_file():
        print(f"error: corpus manifest missing: {manifest_path}", file=sys.stderr)
        return 2
    manifest = json.loads(manifest_path.read_bytes().decode("utf-8"))

    if manifest.get("schema") != SCHEMA:
        problems.append(
            f"manifest schema {manifest.get('schema')!r} != tool {SCHEMA!r}; "
            "regenerate the corpus and commit it with the tool change"
        )
    if manifest.get("params") != PARAMS:
        problems.append(
            "corpus shape parameters drifted from tools/fixturegen.py; "
            "regenerate the corpus and commit it with the tool change"
        )

    manifest_entries = {
        entry["path"]: (entry["sha256"], entry["bytes"])
        for entry in manifest.get("files", [])
    }
    disk_files: dict[str, bytes] = {}
    for path in sorted(
        p.relative_to(corpus_dir).as_posix()
        for p in corpus_dir.rglob("*")
        if p.is_file() and p.name != MANIFEST_NAME
    ):
        disk_files[path] = (corpus_dir / path).read_bytes()

    for path in sorted(set(manifest_entries) - set(disk_files)):
        problems.append(f"manifest file missing from working tree: {path}")
    for path in sorted(set(disk_files) - set(manifest_entries)):
        problems.append(f"working-tree file absent from manifest: {path}")

    seed = manifest.get("seed")
    if not isinstance(seed, str) or not seed:
        problems.append("manifest records no usable seed")
        seed = ""

    if disk_files and manifest.get("corpus_digest") != corpus_digest(disk_files):
        problems.append("manifest corpus_digest does not match the recorded files")

    regenerated, _ = build_corpus(seed)
    for path in sorted(set(regenerated) & set(disk_files)):
        expected = regenerated[path]
        actual = disk_files[path]
        if actual != expected:
            problems.append(
                f"regeneration not byte-identical: {path} "
                f"(recorded {len(actual)} bytes, regenerated {len(expected)})"
            )
        digest, size = manifest_entries.get(path, ("", -1))
        if sha256_hex(actual) != digest or len(actual) != size:
            problems.append(f"working tree does not match manifest digest: {path}")

    problems.extend(scan_corpus(disk_files))

    if problems:
        print(f"error: {len(problems)} fixture verification problem(s):", file=sys.stderr)
        for problem in problems:
            print(f"  - {problem}", file=sys.stderr)
        return 2

    print(f"schema: {SCHEMA} (scan v{SCAN_VERSION})")
    print(f"seed: {seed}")
    print(f"files: {len(disk_files)}")
    print(f"bytes: {sum(len(v) for v in disk_files.values())}")
    print(f"corpus_digest: {manifest.get('corpus_digest')}")
    print("regeneration: byte-identical")
    print("content scan: clean")
    return 0


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(
        description="Deterministic synthetic fixture generator and verification gate."
    )
    modes = parser.add_mutually_exclusive_group()
    modes.add_argument(
        "--verify", action="store_true",
        help="regenerate from the recorded seed, byte-compare, content-scan (default)",
    )
    modes.add_argument(
        "--generate", metavar="OUTPUT",
        help="write the corpus and manifest to OUTPUT",
    )
    parser.add_argument(
        "--seed", default=CANONICAL_SEED,
        help="seed for --generate (default: the canonical committed seed)",
    )
    parser.add_argument(
        "--root", default=str(ROOT),
        help="repository root for --verify",
    )
    parser.add_argument(
        "--force", action="store_true",
        help="let --generate overwrite a non-empty output directory",
    )
    args = parser.parse_args(argv[1:] or ["--verify"])

    if args.generate:
        return cmd_generate(args)
    return cmd_verify(args)


if __name__ == "__main__":
    sys.exit(main(sys.argv))
